export const constants = {
  tools: [
    { title: 'JSON Beautifier', variant: 'default' },
    { title: 'HTML Viewer', variant: 'default' },
    { title: 'Number to Words', variant: 'default' },
    { title: 'SQL Formatter', variant: 'default' },
    { title: 'Image to Base64', variant: 'default' },
    { title: 'Base64 to Image', variant: 'default' },
    { title: 'HEX to Pantone', variant: 'default' },
    { title: 'Source Code Viewer', variant: 'default' },
    { title: 'Binary to Text', variant: 'default' },
    { title: 'JSON Viewer', variant: 'default' },
    { title: 'JSON Validator', variant: 'default' },
    { title: 'Base64 Decode', variant: 'default' },
    { title: 'Hex to Decimal', variant: 'default' },
    { title: 'XML Viewer', variant: 'default' },
    { title: 'XML to JSON', variant: 'default' },
    { title: 'Encryption-Decryption', variant: 'default' },
    { title: 'Excel to HTML', variant: 'default' },
    { title: 'CSS Validator', variant: 'default' },
    { title: 'XML Validator', variant: 'default' },
    { title: 'JavaScript Validator', variant: 'default' },
    { title: 'CSS Beautifier', variant: 'primary' },
    { title: 'ONLINE JSON EDITOR', variant: 'default' },
    { title: 'Decimal to Hex', variant: 'default' },
    { title: 'Binary to Decimal', variant: 'default' },
    { title: 'ASCII to Text', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
  ],
  newFundata: [
    { title: 'Flag Maker', variant: 'default' },
    { title: 'Code to ASCII', variant: 'default' },
    { title: 'Inches to Pixels', variant: 'default' },
    { title: 'Vertical Font Generator', variant: 'default' },
    { title: 'JSON MultiLine String', variant: 'default' },
    { title: 'JWT Decode', variant: 'default' },
    { title: 'JSON to JSONL Converter', variant: 'default' },
    { title: 'HTML to JSX Converter', variant: 'default' },
    { title: 'Markdown Table Generator', variant: 'default' },
    { title: 'Table to HTML Converter', variant: 'default' },
    { title: 'Scoreboard Online', variant: 'default' },
    { title: 'Latex Table Generator', variant: 'default' },
    { title: 'Cash App Fees Calculator', variant: 'default' },
    { title: 'Plaback Speed Calculator', variant: 'default' },
    { title: 'TOML to JSON Converter', variant: 'default' },
    { title: 'JSON to TOML Converter', variant: 'default' },
    { title: 'TOML Validator', variant: 'default' },
    { title: 'Saiyan Name Generator', variant: 'default' },
    { title: 'Roman Numeral Tattoo', variant: 'default' },
    { title: 'Random Coloring Pages', variant: 'default' },
    { title: 'Tiefling Name generator', variant: 'default' },
    { title: 'Dragonborn Name Generator', variant: 'default' },
    { title: 'Cultist Name Generator', variant: 'default' },
    { title: 'Wizard Name Generator', variant: 'default' },
    { title: 'Random Star War Characters', variant: 'default' },
    { title: 'Animal Fusion Generator', variant: 'default' },
    { title: 'Random Indiana Address', variant: 'default' },
    { title: 'Random Tongue Twister', variant: 'default' },
    { title: 'Random Texas Address', variant: 'default' },
    { title: 'JSON Sorter', variant: 'default' },
    { title: 'Small Text Generator', variant: 'default' },
    { title: 'Meme Generator', variant: 'default' },
    { title: 'Yes or No Generator', variant: 'default' },
    { title: 'Truth or Dare Generator', variant: 'default' },
    { title: 'Random Devil Fruit Generator', variant: 'default' },
    { title: 'Random Color Generator', variant: 'default' },
    { title: 'Random Sports Generator', variant: 'default' },
    { title: 'Random Restaurant Generator', variant: 'default' },
    { title: 'MultiLine to Single Line', variant: 'default' },
    { title: 'Random Candy Generator', variant: 'default' },
    { title: 'Random Disney Movie Generator', variant: 'default' },
    { title: 'Random DC Character Generator', variant: 'default' },
    { title: 'Marvel Character Generator', variant: 'default' },
    { title: 'Pitchch-Kincaid Grade Level', variant: 'default' },
    { title: 'Random Trivia Generator', variant: 'default' },
    { title: 'Random Website Generator', variant: 'default' },
    { title: 'Random Proverb Generator', variant: 'default' },
    { title: 'Memorable Password Generator', variant: 'default' },
    { title: 'Harry Potter Spells Generator', variant: 'default' },
    { title: 'Random New York Address', variant: 'default' },
    { title: 'Random Noun Generator', variant: 'default' },
    { title: 'Random Spanish Word Generator', variant: 'default' },
    { title: 'Random Location Generator', variant: 'default' },
    { title: 'Random Town Generator', variant: 'default' },
    { title: 'Goth Name Generator', variant: 'default' },
    { title: 'Fantasy Name Generator', variant: 'default' },
    { title: 'Victorian Name Generator', variant: 'default' },
    { title: 'Magic School Name', variant: 'default' },
    { title: 'Halloween Costume Generator', variant: 'default' },
    { title: 'Book Title Generator', variant: 'default' },
    { title: 'Disney Character Generator', variant: 'default' },
    { title: 'God Name Generator', variant: 'default' },
    { title: 'Random Setting Generator', variant: 'default' },
    { title: 'Twitch Name Generator', variant: 'default' },
    { title: 'Villager Name Generator', variant: 'default' },
    { title: 'Vampire Name Generator', variant: 'default' },
    { title: 'Dwarf Name Generator', variant: 'default' },
    { title: 'DND Name Generator', variant: 'default' },
    { title: 'Random Kingdom Name Generated', variant: 'default' },
    { title: 'Random Japanese Name Generator', variant: 'default' },
    { title: 'Random School Name Generator', variant: 'default' },
    { title: 'Glitch Text Generator', variant: 'default' },
    { title: 'YAML Cheat Sheet', variant: 'default' },
    { title: 'JSON Cheat Sheet', variant: 'default' },
    { title: 'Random Username Generator', variant: 'default' },
    { title: 'Random Cat Name Generator', variant: 'default' },
    { title: 'Random Food Generator', variant: 'default' },
    { title: 'Scenario Generator', variant: 'default' },
    { title: 'JSON to String', variant: 'default' },
    { title: 'Random New Zealand Address', variant: 'default' },
    { title: 'Random Paragraph Generator', variant: 'default' },
    { title: 'Fake ChatGPT Generator', variant: 'default' },
    { title: 'JavaScript Cheat Sheet', variant: 'default' },
    { title: 'Text Formatter', variant: 'default' },
    { title: 'Time Sheet Calculator', variant: 'default' },
    { title: 'Random Video Game Generator', variant: 'default' },
    { title: 'Address in Spain', variant: 'default' },
    { title: 'Random Actor Generator', variant: 'default' },
    { title: 'Random Song Lyrics', variant: 'default' },
    { title: 'Random Caption Generator', variant: 'default' },
    { title: 'Random Celebrity Generator', variant: 'default' },
    { title: 'Sort XML Online', variant: 'default' },
    { title: 'SVG Viewer', variant: 'default' },
    { title: 'SVG Formatter', variant: 'default' },
    { title: 'Cursed Text Generator', variant: 'default' },
    { title: 'Random Superhero Generator', variant: 'default' },
    { title: 'CSS Selectors Cheat Sheet', variant: 'default' },
    { title: 'HEX to RGBA Converter', variant: 'default' },
    { title: 'Sentence Counter', variant: 'default' },
    { title: 'JSON to One Line', variant: 'default' },
    { title: 'Paragraph Counter', variant: 'default' },
    { title: 'Javascript Tester', variant: 'default' },
    { title: 'Random Pokemon Team Generator', variant: 'default' },
    { title: 'Vim Cheat Sheet', variant: 'default' },
    { title: 'Random Canada Address Generator', variant: 'default' },
    { title: 'Random Pokemon Generator', variant: 'default' },
    { title: 'Random Address in California', variant: 'default' },
    { title: 'Random Movie Generator', variant: 'default' },
    { title: 'Character Trait Generator', variant: 'default' },
    { title: 'Random Flower Generator', variant: 'default' },
    { title: 'Random Quote Generator', variant: 'default' },
    { title: 'Random Sentence Generator', variant: 'default' },
    { title: 'Random Element Generator', variant: 'default' },
    { title: 'Random Planet Generator', variant: 'default' },
    { title: 'Random Holiday Generator', variant: 'default' },
    { title: 'Random Last Name Generator', variant: 'default' },
    { title: 'Random Cat Generator', variant: 'default' },
    { title: 'Random College Generator', variant: 'default' },
    { title: 'Random Bird Generator', variant: 'default' },
    { title: 'Random Book Generator', variant: 'default' },
    { title: 'Random Job Generator', variant: 'default' },
    { title: 'Random Link Generator', variant: 'default' },
    { title: 'Tweet to Image Converter', variant: 'default' },
    { title: 'PSN Name Generator', variant: 'default' },
    { title: 'Monster Generator', variant: 'default' },
    { title: 'Random League Champion', variant: 'default' },
    { title: 'Random Body Part Generator', variant: 'default' },
    { title: 'Social Tools', variant: 'default' },
    { title: 'Aesthetic Emoji Generator', variant: 'default' },
    { title: 'Random Superpower Generator', variant: 'default' },
    { title: 'Random Anime Character Generator', variant: 'default' },
    { title: 'Random Dinosaur Generator', variant: 'default' },
    { title: 'Fursona Generator', variant: 'default' },
    { title: 'Sims 3 Trait Generator', variant: 'default' },
    { title: 'Random Emotion Generator', variant: 'default' },
    { title: 'Random Year Generator', variant: 'default' },
    { title: 'Random Lorem Character Generator', variant: 'default' },
    { title: 'Random 6 Digit Number Generated', variant: 'default' },
    { title: 'Random 4 Digit Number Generated', variant: 'default' },
    { title: 'Random Birthday Generator', variant: 'default' },
    { title: 'Letter Randomizer', variant: 'default' },
    { title: 'Text Replacer', variant: 'default' },
    { title: 'Random Tarot Card Generator', variant: 'default' },
    { title: 'Random Dog Breed Generator', variant: 'default' },
    { title: 'Random Car Generator', variant: 'default' },
    { title: 'Lord Of The Rings Name Generator', variant: 'default' },
    { title: 'Fortune Cookie Generator', variant: 'default' },
    { title: 'Random Character Generator', variant: 'default' },
    { title: 'Instagram Caption Generator', variant: 'default' },
    { title: 'Snapchat Fonts Generator', variant: 'default' },
    { title: 'Reddit Username Generator', variant: 'default' },
    { title: 'Random Adjectives Generator', variant: 'default' },
    { title: 'Goofy Ahh Names Generator', variant: 'default' },
    { title: 'Random City Generator', variant: 'default' },
    { title: 'Personality Generator', variant: 'default' },
    { title: 'Random Girl Name Generator', variant: 'default' },
    { title: 'Random State Generator', variant: 'default' },
    { title: 'Full White Screen', variant: 'default' },
    { title: 'Full Blue Screen', variant: 'default' },
    { title: 'Full Red Screen', variant: 'default' },
    { title: 'Full Black Screen', variant: 'default' },
    { title: 'Aesthetic Username Generator', variant: 'default' },
    { title: 'Word Replacer', variant: 'default' },
    { title: 'Moodboard Generator', variant: 'default' },
    { title: 'Valorant Crosshair Generator', variant: 'default' },
    { title: 'Cookie Run Character Generator', variant: 'default' },
    { title: 'JoJo Stand Generator', variant: 'default' },
    { title: 'OTP Prompt Generator', variant: 'default' },
    { title: 'Random Minecraft Block Generator', variant: 'default' },
    { title: 'Random Theme Generator', variant: 'default' },
    { title: 'SQL Code Generator', variant: 'default' },
    { title: 'Random Pokemon Type Generator', variant: 'default' },
    { title: 'Fake Instagram Post Generator', variant: 'default' },
    { title: 'Random Aesthetic Generator', variant: 'default' },
    { title: 'Random Environment Generator', variant: 'default' },
    { title: 'Random Scene Generator', variant: 'default' },
    { title: 'XBOX GamerTag Generator', variant: 'default' },
    { title: 'Elf Name Generator', variant: 'default' },
    { title: 'Tatuaka Twitter Radios Generator', variant: 'default' },
    { title: 'XBOX Name Generator', variant: 'default' },
    { title: 'Warrior Cat Name Generator', variant: 'default' },
    { title: 'Fake Tweet Generator', variant: 'default' },
    { title: 'Random Topic Generator', variant: 'default' },
    { title: 'Pictionary Word Generator', variant: 'default' },
    { title: 'Random Things to Draw Generator', variant: 'default' },
    { title: 'Random Nationality Generator', variant: 'default' },
    { title: 'Random Ethnicity Generator', variant: 'default' },
    { title: 'Random Pet Generator', variant: 'default' },
    { title: 'Billing Postal Code Generator', variant: 'default' },
    { title: 'Random Male Name Generator', variant: 'default' },
    { title: 'Random Boy Name Generator', variant: 'default' },
    { title: 'Random Things Generator', variant: 'default' },
    { title: 'Random Milk Term Generator', variant: 'default' },
    { title: 'Random Zip Code', variant: 'default' },
    { title: 'Random Team Generator', variant: 'default' },
    { title: 'Random Billing Address', variant: 'default' },
    { title: 'Random House Address', variant: 'default' },
    { title: 'Random Street Address', variant: 'default' },
    { title: 'Random Address Generator', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Random Flag Generator', variant: 'default' },
    { title: 'Random Country Generator', variant: 'default' },
    { title: 'Random US Area Codes', variant: 'default' },
    { title: 'Random Phone Number', variant: 'default' },
    { title: 'React Formatter', variant: 'default' },
    { title: 'JSON Fixer', variant: 'default' },
    { title: 'JSON Navigator', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'Favicon Generator', variant: 'default' },
    { title: 'CIDR Calculator', variant: 'default' },
    { title: 'Marquee Generator', variant: 'default' },
    { title: 'Meta Tag Generator', variant: 'default' },
    { title: 'Screenshot Beautifier', variant: 'default' },
    { title: 'Tweet Ideas', variant: 'default' },
    { title: 'Number To WhatsApp', variant: 'default' },
    { title: 'Twitter Header Generator', variant: 'default' },
    { title: 'Twitter Image Downloader', variant: 'default' },
    { title: 'Random MLB Team Generator', variant: 'default' },
    { title: 'Random NBA Team Generator', variant: 'default' },
    { title: 'Random NCAA Football Team', variant: 'default' },
    { title: 'Random NCAA Basketball Team', variant: 'default' },
    { title: 'Random IPL Team Generator', variant: 'default' },
    { title: 'Random NFL Team Generator', variant: 'default' },
    { title: 'Random Object Generator', variant: 'default' },
    { title: 'Random Animal Generator', variant: 'default' },
    { title: 'Random Hobby Generator', variant: 'default' },
    { title: 'Code to Image Converter', variant: 'default' },
    { title: 'Multiple URL Opener', variant: 'default' },
    { title: 'Tweet Beautifier', variant: 'default' },
    { title: 'GIF Viewer', variant: 'default' },
    { title: 'GIF Splitter', variant: 'default' },
    { title: 'Share Code Snippets', variant: 'default' },
    { title: 'Convert Text to Handwriting', variant: 'default' },
    { title: 'Image Beautifier', variant: 'default' },
    { title: 'SVG to Base64', variant: 'default' },
    { title: 'Turbo Search', variant: 'default' },
    { title: 'Text Cleaner', variant: 'default' },
    { title: 'JSON Cleaner', variant: 'default' },
    { title: 'JSON to Typescript Code', variant: 'default' },
    { title: 'Online Vibration Simulator', variant: 'default' },
    { title: 'JSON to PHP Array Converter', variant: 'default' },
    { title: 'IELTS to CLB', variant: 'default' },
    { title: 'Hyperlink Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Facebook Bold Text', variant: 'default' },
    { title: 'What is My Zodiac Sign', variant: 'default' },
    { title: 'Checksum Calculator', variant: 'default' },
    { title: 'SOAP Formatter', variant: 'default' },
    { title: 'WSDL Formatter', variant: 'default' },
    { title: 'Javascript Pretty Print', variant: 'default' },
    { title: 'Visualize JSON Data Graph', variant: 'default' },
    { title: 'Morse Code Translator', variant: 'default' },
    { title: 'Alphabetical Order', variant: 'default' },
    { title: 'Random AlphaNumenric Generator', variant: 'default' },
    { title: 'Hex to UTF8', variant: 'default' },
    { title: 'Byte to String', variant: 'default' },
    { title: 'UTF8 to ASCII', variant: 'default' },
    { title: 'Curl to PHP', variant: 'default' },
    { title: 'Phone Number to IP', variant: 'default' },
    { title: 'Yaml Parser', variant: 'default' },
    { title: 'XML Converter', variant: 'default' },
    { title: 'Gzip Decompress', variant: 'default' },
    { title: 'HTML Table Generator', variant: 'default' },
    { title: 'HTML Link Generator', variant: 'default' },
    { title: 'MP3 to Base64', variant: 'default' },
    { title: 'Base64 to Text', variant: 'default' },
    { title: 'Base64 to Ascii', variant: 'default' },
    { title: 'STYLUS Compiler', variant: 'default' },
    { title: 'JavaScript Obfuscator', variant: 'default' },
    { title: 'String to JSON Online', variant: 'default' },
    { title: 'YAML Pretty Print', variant: 'default' },
    { title: 'YouTube Thumbnail Grabber', variant: 'default' },
  ],
  trendingTools: [
    { title: 'Bitwise Calculator', variant: 'default' },
    { title: 'Number Sorter', variant: 'default' },
    { title: 'Remove Punctuation', variant: 'default' },
    { title: 'HTML Stripper', variant: 'default' },
    { title: 'Real Time HTML Editor', variant: 'default' },
    { title: 'HTML to Markdown', variant: 'default' },
    { title: 'Markdown to HTML', variant: 'default' },
    { title: 'Lua Minifier', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
    { title: 'Wordpress Password Hash', variant: 'default' },
    { title: 'Mirror Online', variant: 'default' },
    { title: 'PHP Formatter', variant: 'default' },
    { title: 'Image to ASCII Art', variant: 'default' },
    { title: 'SHA256 Hash Generator', variant: 'default' },
    { title: 'SHA512 Hash Generator', variant: 'default' },
    { title: 'Excel Viewer', variant: 'default' },
    { title: 'Paraphrasing tool', variant: 'default' },
    { title: 'Word to HTML', variant: 'default' },
    { title: 'CSV to Excel', variant: 'default' },
    { title: 'Sharelink Generator', variant: 'default' },
  ],
  developmentTools: [
    { title: 'IP Tools', variant: 'default' },
    { title: 'Formatters & Beautifiers', variant: 'default' },
    { title: 'Image Converter Tools', variant: 'default' },
    { title: 'Finance Tools', variant: 'default' },
    { title: 'TSV Tools', variant: 'default' },
    { title: 'JSON Tools', variant: 'default' },
    { title: 'XML Tools', variant: 'default' },
    { title: 'YAML Tools', variant: 'default' },
    { title: 'HTML Tools', variant: 'default' },
    { title: 'CSS Tools', variant: 'default' },
    { title: 'Javascript Tools', variant: 'default' },
    { title: 'CSV Tools', variant: 'default' },
    { title: 'SQL Tools', variant: 'default' },
    { title: 'Color Tools', variant: 'default' },
    { title: 'Unit Tools', variant: 'default' },
    { title: 'Number Tools', variant: 'default' },
    { title: 'String Tools', variant: 'default' },
    { title: 'Base64 Tools', variant: 'default' },
    { title: 'Random Tools', variant: 'default' },
    { title: 'Minifiers', variant: 'default' },
    { title: 'Validators', variant: 'default' },
    { title: 'Cryptography', variant: 'default' },
    { title: 'Escape Unescape Tools', variant: 'default' },
    { title: 'UTF Tools', variant: 'default' },
    { title: 'Compress Decompress', variant: 'default' },
    { title: 'HTML Generators', variant: 'default' },
    { title: 'CSS Generators', variant: 'default' },
    { title: 'Other Tools', variant: 'default' },
    { title: 'Text Style Tools', variant: 'default' },
    { title: 'CSS Unit Converter Tools', variant: 'default' },
    { title: 'POJO Tools', variant: 'default' },
    { title: 'Twitter Tools', variant: 'default' },
    { title: 'Random Generators', variant: 'default' },
  ],
};
export const category = [
  
  {
    name: 'SQL Converters', href: '/sql-converters',
    subcategories: [
      { name: 'SQL to CSV Converter', to: 'SQL-Converters/sql-to-csv' },
      { name: 'SQL to JSON Converter', to: 'SQL-Converters/sql-to-json' },
      { name: 'SQL to XML Converter', to: 'SQL-Converters/sql-to-xml' },
      { name: 'SQL to YAML Converter', to: 'SQL-Converters/sql-to-yaml' },
      { name: 'SQL to HTML Converter', to: 'SQL-Converters/sql-to-html' }
    ]
  },
  {
    name: 'Encode & Decode', href: '/encode-&-decode',
    subcategories: [
      { name: 'Base32 Encode', to: 'Encode&-Decode/base32-encode' },
      { name: 'Base32 Decode', to: 'Encode-&-Decode/base32-decode' },
      { name: 'Base58 Encode', to: 'Encode-&-Decode/base58-encode' },
      { name: 'Base58 Decode', to: 'Encode-&-Decode/base58-decode' },
      { name: 'Base64 Encode', to: 'Encode-&-Decode/base64-encode' },
      { name: 'Base64 Decode', to: 'vbase64-decode' },
      { name: 'URL Encode Online', to: 'Encode-&-Decode/url-encode' },
      { name: 'URL Decode Online', to: 'Encode-&-Decode/url-decode' },
      { name: 'JSON URL Encode', to: 'Encode-&-Decode/json-url-encode' },
      { name: 'JSON URL Decode', to: 'Encode-&-Decode/json-url-decode' },
      { name: 'HTML Encode', to: 'Encode-&-Decode/html-encode' },
      { name: 'HTML Decode', to: 'Encode-&-Decode/html-decode' },
      { name: 'XML URL Encoding', to: 'Encode-&-Decode/xml-url-encode' },
      { name: 'XML URL Decoding', to: 'Encode-&-Decode/xml-url-decode' },
      { name: 'UTF8 Converter', to: 'Encode-&-Decode/utf8-converter' },
      { name: 'UTF8 Decode', to: 'Encode-&-Decode/utf8-decode' },
      { name: 'Hex to UTF8', to: 'Encode-&-Decode/hex-to-utf8' },
      { name: 'JSON Decode Online', to: 'Encode-&-Decode/json-decode' },
      { name: 'JSON Encode Online', to: 'Encode-&-Decode/json-encode' }
    ]
  },
  {
    name: 'Base64 Tools', href: '/base64-tools',
    subcategories: [
      { name: 'Image to Base64', to: 'Base64-Tools/image-to-base64' },
      { name: 'Base64 to Image', to: 'Base64-Tools/base64-to-image' },
      { name: 'PNG to Base64', to: 'Base64-Tools/png-to-base64' },
      { name: 'JPG to Base64', to: 'Base64-Tools/jpg-to-base64' },
      { name: 'JSON to Base64', to: 'Base64-Tools/json-to-base64' },
      { name: 'XML to Base64', to: 'Base64-Tools/xml-to-base64' },
      { name: 'YAML to Base64', to: 'Base64-Tools/yaml-to-base64' },
      { name: 'Base64 to JSON', to: 'Base64-Tools/base64-to-json' },
      { name: 'Base64 to XML', to: 'Base64-Tools/base64-to-xml' },
      { name: 'Base64 to YAML', to: 'Base64-Tools/base64-to-yaml' },
      { name: 'CSV to Base64', to: 'Base64-Tools/csv-to-base64' },
      { name: 'Base64 to CSV', to: 'Base64-Tools/base64-to-csv' },
      { name: 'TSV to Base64', to: 'Base64-Tools/tsv-to-base64' },
      { name: 'Base64 to TSV', to: 'Base64-Tools/base64-to-tsv' },
      { name: 'Binary to Base64', to: 'Base64-Tools/binary-to-base64' },
      { name: 'Base64 to Binary', to: 'Base64-Tools/base64-to-binary' },
      { name: 'Hex to Base64', to: 'Base64-Tools/hex-to-base64' },
      { name: 'Base64 to Hex', to: 'Base64-Tools/base64-to-hex' },
      { name: 'Octal to Base64', to: 'Base64-Tools/octal-to-base64' },
      { name: 'More Base64 Tools', to: 'Base64-Tools/more-base64-tools' }
    ]
  },
  {
    name: 'Image Tools', href: '/image-tools',
    subcategories: [
      { name: 'JPG to PNG', to: 'Image-Tools/jpg-to-png' },
      { name: 'BMP to PNG', to: 'Image-Tools/bmp-to-png' },
      { name: 'PNG to JPG', to: 'Image-Tools/png-to-jpg' },
      { name: 'GIF Splitter', to: 'Image-Tools/gif-splitter' },
      { name: 'GIF Viewer', to: 'Image-Tools/gif-viewer' },
      { name: 'More Image Tools', to: 'Image-Tools/more-image-tools' }
    ]
  },
 
  {
    name: 'JSON Converters', href: '/json-converters',
    subcategories: [
      { name: 'JSON to JAVA', to: 'JSON-Converters/json-to-java' },
      { name: 'JSON to XML', to: 'JSON-Converters/json-to-xml' },
      { name: 'JSON to YAML', to: 'JSON-Converters/json-to-yaml' },
      { name: 'JSON to CSV', to: 'JSON-Converters/json-to-csv' },
      { name: 'JSON to TSV', to: 'JSON-Converters/json-to-tsv' },
      { name: 'JSON to Text', to: 'JSON-Converters/json-to-text' },
      { name: 'JSON to Excel', to: 'JSON-Converters/json-to-excel' },
      { name: 'JSON to HTML', to: 'JSON-Converters/json-to-html' }
    ]
  },
  {
    name: 'XML Converters', href: '/xml-converters',
    subcategories: [
      { name: 'XML Converter', to: 'XML-Converters/xml-converter' },
      { name: 'XML to JSON', to: 'XML-Converters/xml-to-json' },
      { name: 'XML to YAML', to: 'XML-Converters/xml-to-yaml' },
      { name: 'XML to CSV', to: 'XML-Converters/xml-to-csv' },
      { name: 'XML to TSV', to: 'XML-Converters/xml-to-tsv' },
      { name: 'XML to Text', to: 'XML-Converters/xml-to-text' },
      { name: 'XML-XSL Transform', to: 'XML-Converters/xml-xsl-transform' },
      { name: 'XML to HTML', to: 'XML-Converters/xml-to-html' },
      { name: 'XML to Excel', to: 'XML-Converters/xml-to-excel' },
      { name: 'XML to JAVA', to: 'XML-Converters/xml-to-java' }
    ]
  },
  {
    name: 'HTML Converters', href: '/html-converters',
    subcategories: [
      { name: 'HTML Stripper', to: 'html-stripper' },
      { name: 'HTML Table Generator', to: 'HTML-Converters/html-table-generator' },
      { name: 'HTML to CSV Converter', to: 'HTML-Converters/html-to-csv-converter' },
      { name: 'HTML to TSV Converter', to: 'HTML-Converters/html-to-tsv-converter' },
      { name: 'HTML to PHP Converter', to: 'HTML-Converters/html-to-php-converter' },
      { name: 'HTML to CSV', to: 'HTML-Converters/html-to-csv' },
      { name: 'HTML to JSON', to: 'HTML-Converters/html-to-json' },
      { name: 'HTML to XML', to: 'HTML-Converters/html-to-xml' },
      { name: 'HTML to YAML', to: 'HTML-Converters/html-to-yaml' },
      { name: 'HTML to Text', to: 'HTML-Converters/html-to-text' },
      { name: 'Text to HTML Entities', to: 'HTML-Converters/text-to-html-entities' },
      { name: 'HTML Entities to Text', to: 'HTML-Converters/html-entities-to-text' },
      { name: 'HTML to Markdown', to: 'HTML-Converters/html-to-markdown' },
      { name: 'Markdown to HTML', to: 'HTML-Converters/markdown-to-html' },
      { name: 'PUG to HTML Converter', to: 'HTML-Converters/pug-to-html-converter' },
      { name: 'HTML to PUG Converter', to: 'HTML-Converters/html-to-pug-converter' },
      { name: 'JADE to HTML Converter', to: 'HTML-Converters/jade-to-html-converter' },
      { name: 'HTML to JADE Converter', to: 'HTML-Converters/html-to-jade-converter' },
      { name: 'HTML to BBCode Converter', to: 'HTML-Converters/html-to-bbcode-converter' },
      { name: 'BBCode to HTML Converter', to: 'HTML-Converters/bbcode-to-html-converter' }
    ]
  },
  {
    name: 'YAML Converters', href: '/yaml-converters',
    subcategories: [
      { name: 'YAML Converter', to: 'YAML-Converters/yaml-converter' },
      { name: 'YAML to XML', to: 'YAML-Converters/yaml-to-xml' },
      { name: 'YAML to JSON', to: 'YAML-Converters/yaml-to-json' },
      { name: 'YAML to CSV', to: 'YAML-Converters/yaml-to-csv' },
      { name: 'YAML to Excel', to: 'YAML-Converters/yaml-to-excel' }
    ]
  },
  {
    name: 'Utility', href: '/utility',
    subcategories: [
      { name: 'Send Snap Message', to: 'Utility/send-snap-message' },
      { name: 'Responsive Website Tester', to: 'Utility/responsive-website-tester' },
      { name: 'Credit Card Validator', to: 'Utility/credit-card-validator' },
      { name: 'Credit Card Fake Number Generator', to: 'Utility/credit-card-fake-number-generator' },
      { name: 'XPath Tester', to: 'Utility/xpath-tester' },
      { name: 'JSON Path Tester', to: 'Utility/json-path-tester' },
      { name: 'JSON Minifier', to: 'Utility/json-minifier' },
      { name: 'File Difference', to: 'Utility/file-difference' },
      { name: 'JSON Diff', to: 'Utility/json-diff' },
      { name: 'XML Diff', to: 'Utility/xml-diff' },
      { name: 'Broken Link Checker', to: 'Utility/broken-link-checker' },
      { name: 'JSON Deserialize Online', to: 'Utility/json-deserialize-online' },
      { name: 'JSON Serialize Online', to: 'Utility/json-serialize-online' },
      { name: 'JSON Stringify Online', to: 'Utility/json-stringify-online' },
      { name: 'XML Stringify Online', to: 'Utility/xml-stringify-online' },
      { name: 'String to JSON Online', to: 'Utility/string-to-json-online' },
      { name: 'JavaScript Obfuscator', to: 'Utility/javascript-obfuscator' },
      { name: 'Curl to PHP', to: 'Utility/curl-to-php' },
      { name: 'Crontab Format', to: 'Utility/crontab-format' }
    ]
  },
  // {
  //   name: 'Chart Tools', href: '/chart-tools',
  //   subcategories: [
  //     { name: 'Line Graph Maker', to: 'chart-tools/line-graph-maker' },
  //     { name: 'Bar Graph Maker', to: 'chart-tools/bar-graph-maker' },
  //     { name: 'Pie Chart Maker', to: 'chart-tools/pie-chart-maker' },
  //     { name: 'Doughnut Chart Maker', to: 'chart-tools/doughnut-chart-maker' },
  //     { name: 'Scatter Plot Maker', to: 'chart-tools/scatter-plot-maker' }
  //   ]
  // },
  // {
  //   name: 'Viewers', href: '/viewers',
  //   subcategories: [
  //     { name: 'JSON Viewer', to: 'Viewers/json-viewer' },
  //     { name: 'XML Viewer', to: 'Viewers/xml-viewer' },
  //     { name: 'YAML Viewer', to: 'Viewers/yaml-viewer' },
  //     { name: 'MXML Viewer', to: 'Viewers/mxml-viewer' },
  //     { name: 'HTML Viewer', to: 'Viewers/html-viewer' },
  //     { name: 'JavaScript Viewer', to: 'Viewers/javascript-viewer' },
  //     { name: 'RSS Viewer', to: 'Viewers/rss-viewer' },
  //     { name: 'SOURCE CODE Viewer', to: 'Viewers/source-code-viewer' },
  //     { name: 'OPML Viewer', to: 'Viewers/opml-viewer' },
  //     { name: 'CSV Viewer', to: 'Viewers/csv-viewer' },
  //     { name: 'BBCode Viewer', to: 'Viewers/bbcode-viewer' },
  //     { name: 'Markdown Viewer', to: 'Viewers/markdown-viewer' }
  //   ]
  // },
  // {
  //   name: 'Programming Editors', href: '/programming-editors',
  //   subcategories: [
  //     { name: 'XML Editor', to: 'Programming-Editors/xml-editor' },
  //     { name: 'JSON Editor', to: 'Programming-Editors/json-editor' },
  //     { name: 'Real Time HTML Editor', to: 'Programming-Editors/real-time-html-editor' },
  //     { name: 'YAML Editor', to: 'Programming-Editors/yaml-editor' },
  //     { name: 'ONLINE Editor', to: 'Programming-Editors/online-editor' },
  //     { name: 'JAVA Editor', to: 'Programming-Editors/java-editor' },
  //     { name: 'C# Editor', to: 'Programming-Editors/csharp-editor' },
  //     { name: 'Actionscript Editor', to: 'Programming-Editors/actionscript-editor' },
  //     { name: 'Markdown Editor', to: 'Programming-Editors/markdown-editor' }
  //   ]
  // },
  // {
  //   name: 'Parsers', href: '/parsers',
  //   subcategories: [
  //     { name: 'URL Parser', to: 'Parsers/url-parser' },
  //     { name: 'JSON Parser', to: 'Parsers/json-parser' },
  //     { name: 'XML Parser', to: 'Parsers/xml-parser' },
  //     { name: 'YAML Parser', to: 'Parsers/yaml-parser' }
  //   ]
  // },
  // {
  //   name: 'CSS Tools', href: '/css-tools',
  //   subcategories: [
  //     { name: 'CSS Beautifier', to: 'CSS-Tools/css-beautifier' },
  //     { name: 'CSS to LESS', to: 'CSS-Tools/css-to-less' },
  //     { name: 'CSS to SCSS', to: 'CSS-Tools/css-to-scss' },
  //     { name: 'CSS to SASS', to: 'CSS-Tools/css-to-sass' },
  //     { name: 'CSS to Stylus', to: 'CSS-Tools/css-to-stylus' },
  //     { name: 'Stylus Compiler', to: 'CSS-Tools/stylus-compiler' },
  //     { name: 'Stylus to CSS', to: 'CSS-Tools/stylus-to-css' },
  //     { name: 'Stylus to LESS', to: 'CSS-Tools/stylus-to-less' },
  //     { name: 'Stylus to SCSS', to: 'CSS-Tools/stylus-to-scss' },
  //     { name: 'Stylus to SASS', to: 'CSS-Tools/stylus-to-sass' },
  //     { name: 'LESS Compiler', to: 'CSS-Tools/less-compiler' },
  //     { name: 'LESS to CSS', to: 'CSS-Tools/less-to-css' },
  //     { name: 'LESS to Stylus', to: 'CSS-Tools/less-to-stylus' },
  //     { name: 'LESS to SCSS', to: 'CSS-Tools/less-to-scss' },
  //     { name: 'LESS to SASS', to: 'CSS-Tools/less-to-sass' },
  //     { name: 'SCSS Compiler', to: 'CSS-Tools/scss-compiler' },
  //     { name: 'SCSS to CSS', to: 'CSS-Tools/scss-to-css' },
  //     { name: 'SCSS to Stylus', to: 'CSS-Tools/scss-to-stylus' },
  //     { name: 'SCSS to LESS', to: 'CSS-Tools/scss-to-less' },
  //     { name: 'SCSS to SASS', to: 'CSS-Tools/scss-to-sass' },
  //     { name: 'SASS Compiler', to: 'CSS-Tools/sass-compiler' },
  //     { name: 'SASS to CSS', to: 'CSS-Tools/sass-to-css' },
  //     { name: 'SASS to Stylus', to: 'CSS-Tools/sass-to-stylus' },
  //     { name: 'SASS to SCSS', to: 'CSS-Tools/sass-to-scss' },
  //     { name: 'SASS to LESS', to: 'CSS-Tools/sass-to-less' }
  //   ]
  // },
  // {
  //   name: 'Escape Unescape', href: '/escape-unescape',
  //   subcategories: [
  //     { name: 'HTML Escape Unescape', to: 'Escape-Unescape/html-escape-unescape' },
  //     { name: 'XML Escape Unescape', to: 'Escape-Unescape/xml-escape-unescape' },
  //     { name: 'Java Escape Unescape', to: 'Escape-Unescape/java-escape-unescape' },
  //     { name: 'C# Escape Unescape', to: 'Escape-Unescape/csharp-escape-unescape' },
  //     { name: 'Javascript Escape Unescape', to: 'Escape-Unescape/javascript-escape-unescape' },
  //     { name: 'CSV Escape Unescape', to: 'Escape-Unescape/csv-escape-unescape' },
  //     { name: 'SQL Escape Unescape', to: 'Escape-Unescape/sql-escape-unescape' },
  //     { name: 'JSON Escape Unescape', to: 'Escape-Unescape/json-escape-unescape' },
  //     { name: 'Un-Google Link', to: 'Escape-Unescape/un-google-link' }
  //   ]
  // },
  // {
  //   name: 'CryptoGraphy Tools', href: '/cryptography-tools',
  //   subcategories: [
  //     { name: 'Encryption-Decryption', to: 'CryptoGraphy-Tools/encryption-decryption' },
  //     { name: 'HMAC Generator', to: 'CryptoGraphy-Tools/hmac-generator' },
  //     { name: 'MD2 Hash Generator', to: 'CryptoGraphy-Tools/md2-hash-generator' },
  //     { name: 'MD4 Hash Generator', to: 'CryptoGraphy-Tools/md4-hash-generator' },
  //     { name: 'MD5 Hash Generator', to: 'CryptoGraphy-Tools/md5-hash-generator' },
  //     { name: 'MD6 Hash Generator', to: 'CryptoGraphy-Tools/md6-hash-generator' },
  //     { name: 'NTLM Hash Generator', to: 'CryptoGraphy-Tools/ntlm-hash-generator' },
  //     { name: 'SHA1 Hash Generator', to: 'CryptoGraphy-Tools/sha1-hash-generator' },
  //     { name: 'SHA2 Hash Generator', to: 'CryptoGraphy-Tools/sha2-hash-generator' },
  //     { name: 'SHA224 Hash Generator', to: 'CryptoGraphy-Tools/sha224-hash-generator' },
  //     { name: 'SHA256 Hash Generator', to: 'CryptoGraphy-Tools/sha256-hash-generator' },
  //     { name: 'SHA384 Hash Generator', to: 'CryptoGraphy-Tools/sha384-hash-generator' },
  //     { name: 'SHA512 Hash Generator', to: 'CryptoGraphy-Tools/sha512-hash-generator' },
  //     { name: 'SHA512/224 Hash Generator', to: 'CryptoGraphy-Tools/sha512-224-hash-generator' },
  //     { name: 'SHA512/256 Hash Generator', to: 'CryptoGraphy-Tools/sha512-256-hash-generator' },
  //     { name: 'SHA3-224 Hash Generator', to: 'CryptoGraphy-Tools/sha3-224-hash-generator' },
  //     { name: 'SHA3-256 Hash Generator', to: 'CryptoGraphy-Tools/sha3-256-hash-generator' },
  //     { name: 'SHA3-384 Hash Generator', to: 'CryptoGraphy-Tools/sha3-384-hash-generator' },
  //     { name: 'SHA3-512 Hash Generator', to: 'CryptoGraphy-Tools/sha3-512-hash-generator' },
  //     { name: 'CRC-16 Hash Generator', to: 'CryptoGraphy-Tools/crc-16-hash-generator' },
  //     { name: 'CRC-32 Hash Generator', to: 'CryptoGraphy-Tools/crc-32-hash-generator' },
  //     { name: 'Shake-128 Hash Generator', to: 'CryptoGraphy-Tools/shake-128-hash-generator' },
  //     { name: 'Shake-256 Hash Generator', to: 'CryptoGraphy-Tools/shake-256-hash-generator' },
  //     { name: 'Whirlpool Hash Generator', to: 'CryptoGraphy-Tools/whirlpool-hash-generator' },
  //     { name: 'Wordpress Password Hash Generator', to: 'CryptoGraphy-Tools/wordpress-password-hash-generator' }
  //   ]
  // },
  // {
  //   name: 'Beautifiers', href: '/beautifiers',
  //   subcategories: [
  //     { name: 'JSON Beautifier', to: 'Beautifiers/json-beautifier' },
  //     { name: 'CSS Beautifier', to: 'Beautifiers/css-beautifier' },
  //     { name: 'XML Beautifier', to: 'Beautifiers/xml-beautifier' },
  //     { name: 'Javascript Beautifier', to: 'Beautifiers/javascript-beautifier' },
  //     { name: 'YAML Beautifier', to: 'Beautifiers/yaml-beautifier' },
  //     { name: 'C# Beautifier', to: 'Beautifiers/csharp-beautifier' },
  //     { name: 'Java Beautifier', to: 'Beautifiers/java-beautifier' },
  //     { name: 'C Beautifier', to: 'Beautifiers/c-beautifier' },
  //     { name: 'C++ Beautifier', to: 'Beautifiers/cpp-beautifier' },
  //     { name: 'TypeScript Formatter', to: 'Beautifiers/typescript-formatter' },
  //     { name: 'SQL Formatter', to: 'Beautifiers/sql-formatter' },
  //     { name: 'Babel Formatter', to: 'Beautifiers/babel-formatter' },
  //     { name: 'Markdown Formatter', to: 'Beautifiers/markdown-formatter' },
  //     { name: 'MDX Formatter', to: 'Beautifiers/mdx-formatter' },
  //     { name: 'LESS Beautifier', to: 'Beautifiers/less-beautifier' },
  //     { name: 'SCSS Beautifier', to: 'Beautifiers/scss-beautifier' },
  //     { name: 'GraphQL Beautifier', to: 'Beautifiers/graphql-beautifier' },
  //     { name: 'PHP Beautifier', to: 'Beautifiers/php-beautifier' },
  //     { name: 'Python Beautifier', to: 'Beautifiers/python-beautifier' },
  //     { name: 'Perl Beautifier', to: 'Beautifiers/perl-beautifier' },
  //     { name: 'Ruby Beautifier', to: 'Beautifiers/ruby-beautifier' },
  //     { name: 'Angular Formatter', to: 'Beautifiers/angular-formatter' },
  //     { name: 'React Formatter', to: 'Beautifiers/react-formatter' },
  //     { name: 'Lua Beautifier', to: 'Beautifiers/lua-beautifier' },
  //     { name: 'XAML Beautifier', to: 'Beautifiers/xaml-beautifier' }
  //   ]
  // },
  // {
  //   name: 'Minifier', href: '/minifier',
  //   subcategories: [
  //     { name: 'JSON Minify', to: 'json-minify' },
  //     { name: 'XML Minify', to: 'xml-minify' },
  //     { name: 'Minify JS', to: 'minify-js' },
  //     { name: 'CSS Minify', to: 'css-minify' },
  //     { name: 'SQL Minifier', to: 'sql-minifier' },
  //     { name: 'Minify HTML', to: 'minify-html' },
  //     { name: 'Lua Minifier', to: 'lua-minifier' },
  //     { name: 'Text Minifier', to: 'text-minifier' }
  //   ]
  // },
  // {
  //   name: 'CSV Tools', href: '/csv-tools',
  //   subcategories: [
  //     { name: 'CSV Viewer', to: 'csv-viewer' },
  //     { name: 'CSV to XML/JSON', to: 'csv-to-xml-json' },
  //     { name: 'CSV to XML', to: 'csv-to-xml' },
  //     { name: 'CSV to JSON', to: 'csv-to-json' },
  //     { name: 'CSV to HTML', to: 'csv-to-html' },
  //     { name: 'CSV to TSV', to: 'csv-to-tsv' },
  //     { name: 'CSV to MULTILINE DATA', to: 'csv-to-multiline-data' },
  //     { name: 'CSV to SQL', to: 'csv-to-sql' },
  //     { name: 'CSV to Excel', to: 'csv-to-excel' }
  //   ]
  // },
  // {
  //   name: 'String Utilities', href: '/string-utilities',
  //   subcategories: [
  //     { name: 'Random Word Generator', to: 'random-word-generator' },
  //     { name: 'NTLM Hash Generator', to: 'ntlm-hash-generator' },
  //     { name: 'Password Generator', to: 'password-generator' },
  //     { name: 'String Builder', to: 'string-builder' },
  //     { name: 'Number to Word Converter', to: 'number-to-word-converter' },
  //     { name: 'Word to Number Converter', to: 'word-to-number-converter' },
  //     { name: 'WORD COUNTER', to: 'word-counter' },
  //     { name: 'Word Repeater', to: 'word-repeater' },
  //     { name: 'Reverse String', to: 'reverse-string' },
  //     { name: 'String to Hex Converter', to: 'string-to-hex-converter' },
  //     { name: 'Hex to String Converter', to: 'hex-to-string-converter' },
  //     { name: 'String to Binary Converter', to: 'string-to-binary-converter' },
  //     { name: 'Binary to String Converter', to: 'binary-to-string-converter' },
  //     { name: 'Case Converter', to: 'case-converter' },
  //     { name: 'Delimited Text Extractor', to: 'delimited-text-extractor' },
  //     { name: 'Remove Accents', to: 'remove-accents' },
  //     { name: 'Remove Duplicate Lines', to: 'remove-duplicate-lines' },
  //     { name: 'Remove Empty Lines', to: 'remove-empty-lines' },
  //     { name: 'Remove Extra Spaces', to: 'remove-extra-spaces' },
  //     { name: 'Remove Whitespace', to: 'remove-whitespace' },
  //     { name: 'Remove Line Breaks', to: 'remove-line-breaks' },
  //     { name: 'Remove Lines Containing', to: 'remove-lines-containing' },
  //     { name: 'Sort Text Lines', to: 'sort-text-lines' },
  //     { name: 'Word Sorter', to: 'word-sorter' },
  //     { name: 'Word Frequency Counter', to: 'word-frequency-counter' },
  //     { name: 'Text Repeater', to: 'text-repeater' },
  //     { name: 'Remove Punctuation', to: 'remove-punctuation' }
  //   ]
  // },
  // {
  //   name: 'Syntax Highlighting', href: '/syntax-highlighting',
  //   subcategories: [
  //     { name: 'JSON Syntax Highlighting', to: 'json-syntax-highlighting' },
  //     { name: 'XML Highlighter', to: 'xml-highlighter' },
  //     { name: 'XML Pretty Print', to: 'xml-pretty-print' },
  //     { name: 'HTML Pretty Print', to: 'html-pretty-print' },
  //     { name: 'JS Pretty Print', to: 'js-pretty-print' },
  //     { name: 'Code Highlighter', to: 'code-highlighter' }
  //   ]
  // },
  // {
  //   name: 'Compress / Decompress', href: '/compress-decompress',
  //   subcategories: [
  //     { name: 'GZip Decompress Online', to: 'gzip-decompress-online' },
  //     { name: 'Zlib Decompress Online', to: 'zlib-decompress-online' }
  //   ]
  // },
  // {
  //   name: 'Validators', href: '/validators',
  //   subcategories: [
  //     { name: 'CSS Validator', to: 'css-validator' },
  //     { name: 'JavaScript Validator', to: 'javascript-validator' },
  //     { name: 'JSON Validator', to: 'json-validator' },
  //     { name: 'JSON5 Validator', to: 'json5-validator' },
  //     { name: 'XML Validator', to: 'xml-validator' },
  //     { name: 'Credit Card Validator', to: 'credit-card-validator' },
  //     { name: 'API Test', to: 'api-test' },
  //     { name: 'YAML Validator', to: 'yaml-validator' }
  //   ]
  // },
  // {
  //   name: 'Number Utilities', href: '/number-utilities',
  //   subcategories: [
  //     { name: 'All Numbers Converter', to: 'all-numbers-converter' },
  //     { name: 'Decimal to Binary', to: 'decimal-to-binary' },
  //     { name: 'Decimal to Octal', to: 'decimal-to-octal' },
  //     { name: 'Binary to Decimal', to: 'binary-to-decimal' },
  //     { name: 'Binary to Hex', to: 'binary-to-hex' },
  //     { name: 'Binary to Octal', to: 'binary-to-octal' },
  //     { name: 'Hex to Decimal', to: 'hex-to-decimal' },
  //     { name: 'Hex to Binary', to: 'hex-to-binary' },
  //     { name: 'Hex to Octal', to: 'hex-to-octal' },
  //     { name: 'Octal toDecimal', to: 'octal-to-decimal' },
  //     { name: 'Octal to Binary', to: 'octal-to-binary' },
  //     { name: 'Octal to Hex', to: 'octal-to-hex' },
  //     { name: 'Binary to Text', to: 'binary-to-text' },
  //     { name: 'Text to Binary', to: 'text-to-binary' },
  //     { name: 'ASCII to Text', to: 'ascii-to-text' },
  //     { name: 'Char to ASCII', to: 'char-to-ascii' },
  //     { name: 'Reverse Hex', to: 'reverse-hex' }
  //   ]
  // },
  // {
  //   name: 'Bitwise Tools', href: '/bitwise-tools',
  //   subcategories: [
  //     { name: 'Bitwise Calculator', to: 'bitwise-calculator' },
  //     { name: 'XOR Calculator', to: 'xor-calculator' },
  //     { name: 'AND Calculator', to: 'and-calculator' },
  //     { name: 'NAND Calculator', to: 'nand-calculator' },
  //     { name: 'OR Calculator', to: 'or-calculator' },
  //     { name: 'NOR Calculator', to: 'nor-calculator' },
  //     { name: 'XNOR Calculator', to: 'xnor-calculator' }
  //   ]
  // },
  // {
  //   name: 'IP Tools', href: '/ip-tools',
  //   subcategories: [
  //     { name: 'Hex to IP', to: 'hex-to-ip' },
  //     { name: 'IP to Hex', to: 'ip-to-hex' },
  //     { name: 'Binary to IP', to: 'binary-to-ip' },
  //     { name: 'IP to Binary', to: 'ip-to-binary' },
  //     { name: 'Decimal to IP', to: 'decimal-to-ip' },
  //     { name: 'IP to Decimal', to: 'ip-to-decimal' },
  //     { name: 'Octal to IP', to: 'octal-to-ip' },
  //     { name: 'IP to Octal', to: 'ip-to-octal' },
  //     { name: 'IPV6 to Binary', to: 'ipv6-to-binary' }
  //   ]
  // },
  // {
  //   name: 'Other Tools', href: '/other-tools',
  //   subcategories: [
  //     { name: 'Lorem-Ipsum', to: 'lorem-ipsum' },
  //     { name: 'Sharelink Generator', to: 'sharelink-generator' },
  //     { name: 'Hostname to IP', to: 'hostname-to-ip' },
  //     { name: 'IP to Hostname', to: 'ip-to-hostname' },
  //     { name: 'Phone to IP Address', to: 'phone-to-ip-address' },
  //     { name: 'IP Address to Phone', to: 'ip-address-to-phone' },
  //     { name: 'DNS Lookup', to: 'dns-lookup' },
  //     { name: 'MX Lookup', to: 'mx-lookup' },
  //     { name: 'Nameserver Lookup', to: 'nameserver-lookup' },
  //     { name: 'Website to IP Address', to: 'website-to-ip-address' },
  //     { name: 'Open Port Checker', to: 'open-port-checker' },
  //     { name: 'Webcam Test', to: 'webcam-test' }
  //   ]
  // },
  // {
  //   name: 'Random Tools', href: '/random-tools',
  //   subcategories: [
  //     { name: 'Random IP Address', to: 'random-ip-address' },
  //     { name: 'Random Time Generator', to: 'random-time-generator' },
  //     { name: 'Random UUID Generator', to: 'random-uuid-generator' },
  //     { name: 'Random JSON Generator', to: 'random-json-generator' },
  //     { name: 'Random XML Generator', to: 'random-xml-generator' },
  //     { name: 'Random Data from Regex', to: 'random-data-from-regex' },
  //     { name: 'Random CSV Generator', to: 'random-csv-generator' },
  //     { name: 'Random Number Generator', to: 'random-number-generator' },
  //     { name: 'Random Integer Generator', to: 'random-integer-generator' },
  //     { name: 'Random Prime Generator', to: 'random-prime-generator' },
  //     { name: 'Random Date Generator', to: 'random-date-generator' },
  //     { name: 'Random Bitmap Generator', to: 'random-bitmap-generator' },
  //     { name: 'Random Name Picker', to: 'random-name-picker' },
  //     { name: 'Text Lines shuffler', to: 'text-lines-shuffler' },
  //     { name: 'MAC Address Generator', to: 'mac-address-generator' },
  //     { name: 'Random Hex Generator', to: 'random-hex-generator' },
  //     { name: 'Random TSV Generator', to: 'random-tsv-generator' },
  //     { name: 'Random String Generator', to: 'random-string-generator' },
  //     { name: 'Random Fraction Generator', to: 'random-fraction-generator' },
  //     { name: 'Random Integer Range Generator', to: 'random-integer-range-generator' },
  //     { name: 'Random Binary Generator', to: 'random-binary-generator' },
  //     { name: 'Random Byte Generator', to: 'random-byte-generator' },
  //     { name: 'Random Decimal Generator', to: 'random-decimal-generator' },
  //     { name: 'Random Alphanumeric Generator', to: 'random-alphanumeric-generator' }
  //   ]
  // },
  // ... (the rest categories like Converters, JSON Converters, XML Converters, HTML Converters, YAML Converters, Utility, Chart Tools, Viewers, Programming Editors, Parsers, CSS Tools, Escape Unescape, CryptoGraphy Tools, Beautifiers, etc. remain unchanged from your list — just ensure no duplicates)
];

// export const category = [

//   {
//     name: 'Color Converters',
//     subcategories: [
//       { name: 'HEX to Pantone Converter', to: 'hextopantone' },
//       { name: 'RGB to Pantone Converter', to: 'rgbtopantone' },
//       { name: 'HSV to Pantone Converter', to: 'hsvtopantone' },
//       { name: 'CMYK to Pantone Converter', to: 'cmyktopantone' },
//       { name: 'CMYK to HEX Converter', to: 'cmyktohex' },
//       { name: 'CMYK to RGB Converter', to: 'cmyktorgb' },
//       { name: 'CMYK to HSV Converter', to: 'cmyktohsv' },
//       { name: 'HSV to HEX Converter', to: 'hsvtohex' },
//       { name: 'HSV to RGB Converter', to: 'hsvtorgb' },
//       { name: 'HSV to CMYK Converter', to: 'hsvtocmyk' },
//       { name: 'HEX to HSV Converter', to: 'hextohsv' },
//       { name: 'RGB to HEX Converter', to: 'rgbtohex' },
//       { name: 'RGB to HSV Converter', to: 'rgbtohsv' },
//       { name: 'RGB to CMYK Converter', to: 'rgbtocmyk' },
//       { name: 'HEX to RGB Converter', to: 'hextorgb' },
//       { name: 'HEX to CMYK Converter', to: 'hextocmyk' },
//       { name: 'Pantone to HEX Converter', to: 'pantonetohex' },
//       { name: 'Pantone to RGB Converter', to: 'pantonetorgb' },
//       { name: 'Pantone to CMYK Converter', to: 'pantonetocmyk' },
//       { name: 'Pantone to HSV Converter', to: 'pantonetohsv' }
//     ]
//   },
//   {
//     name: 'Color Converters',
//     subcategories: [
//       { name: 'HEX to Pantone Converter', to: 'hextopantone' },
//       { name: 'RGB to Pantone Converter', to: 'rgbtopantone' },
//       { name: 'HSV to Pantone Converter', to: 'hsvtopantone' },
//       { name: 'CMYK to Pantone Converter', to: 'cmyktopantone' },
//       { name: 'CMYK to HEX Converter', to: 'cmyktohex' },
//       { name: 'CMYK to RGB Converter', to: 'cmyktorgb' },
//       { name: 'CMYK to HSV Converter', to: 'cmyktohsv' },
//       { name: 'HSV to HEX Converter', to: 'hsvtohex' },
//       { name: 'HSV to RGB Converter', to: 'hsvtorgb' },
//       { name: 'HSV to CMYK Converter', to: 'hsvtocmyk' },
//       { name: 'HEX to HSV Converter', to: 'hextohsv' },
//       { name: 'RGB to HEX Converter', to: 'rgbtohex' },
//       { name: 'RGB to HSV Converter', to: 'rgbtohsv' },
//       { name: 'RGB to CMYK Converter', to: 'rgbtocmyk' },
//       { name: 'HEX to RGB Converter', to: 'hextorgb' },
//       { name: 'HEX to CMYK Converter', to: 'hextocmyk' },
//       { name: 'Pantone to HEX Converter', to: 'pantonetohex' },
//       { name: 'Pantone to RGB Converter', to: 'pantonetorgb' },
//       { name: 'Pantone to CMYK Converter', to: 'pantonetocmyk' },
//       { name: 'Pantone to HSV Converter', to: 'pantonetohsv' }
//     ]
//   },
//   {
//     name: 'Unit Converter',
//     subcategories: [
//       { name: 'Length Converter', to: 'length-converter' },
//       { name: 'Weight Converter', to: 'weight-converter' },
//       { name: 'Volume Converter', to: 'volume-converter' },
//       { name: 'Area Converter', to: 'area-converter' },
//       { name: 'Time Converter', to: 'time-converter' },
//       { name: 'Unix Timestamp Converter', to: 'unix-timestamp-converter' },
//       { name: 'More Unit Tools', to: 'more-unit-tools' }
//     ]
//   },
//   {
//     name: 'SQL Converters',
//     subcategories: [
//       { name: 'SQL to CSV Converter', to: 'sql-to-csv' },
//       { name: 'SQL to JSON Converter', to: 'sql-to-json' },
//       { name: 'SQL to XML Converter', to: 'sql-to-xml' },
//       { name: 'SQL to YAML Converter', to: 'sql-to-yaml' },
//       { name: 'SQL to HTML Converter', to: 'sql-to-html' }
//     ]
//   },
//   {
//     name: 'Encode & Decode',
//     subcategories: [
//       { name: 'Base32 Encode', to: 'base32-encode' },
//       { name: 'Base32 Decode', to: 'base32-decode' },
//       { name: 'Base58 Encode', to: 'base58-encode' },
//       { name: 'Base58 Decode', to: 'base58-decode' },
//       { name: 'Base64 Encode', to: 'base64-encode' },
//       { name: 'Base64 Decode', to: 'base64-decode' },
//       { name: 'URL Encode Online', to: 'url-encode' },
//       { name: 'URL Decode Online', to: 'url-decode' },
//       { name: 'JSON URL Encode', to: 'json-url-encode' },
//       { name: 'JSON URL Decode', to: 'json-url-decode' },
//       { name: 'HTML Encode', to: 'html-encode' },
//       { name: 'HTML Decode', to: 'html-decode' },
//       { name: 'XML URL Encoding', to: 'xml-url-encode' },
//       { name: 'XML URL Decoding', to: 'xml-url-decode' },
//       { name: 'UTF8 Converter', to: 'utf8-converter' },
//       { name: 'UTF8 Decode', to: 'utf8-decode' },
//       { name: 'Hex to UTF8', to: 'hex-to-utf8' },
//       { name: 'JSON Decode Online', to: 'json-decode' },
//       { name: 'JSON Encode Online', to: 'json-encode' }
//     ]
//   },
//   {
//     name: 'Base64 Tools',
//     subcategories: [
//       { name: 'Image to Base64', to: 'image-to-base64' },
//       { name: 'Base64 to Image', to: 'base64-to-image' },
//       { name: 'PNG to Base64', to: 'png-to-base64' },
//       { name: 'JPG to Base64', to: 'jpg-to-base64' },
//       { name: 'JSON to Base64', to: 'json-to-base64' },
//       { name: 'XML to Base64', to: 'xml-to-base64' },
//       { name: 'YAML to Base64', to: 'yaml-to-base64' },
//       { name: 'Base64 to JSON', to: 'base64-to-json' },
//       { name: 'Base64 to XML', to: 'base64-to-xml' },
//       { name: 'Base64 to YAML', to: 'base64-to-yaml' },
//       { name: 'CSV to Base64', to: 'csv-to-base64' },
//       { name: 'Base64 to CSV', to: 'base64-to-csv' },
//       { name: 'TSV to Base64', to: 'tsv-to-base64' },
//       { name: 'Base64 to TSV', to: 'base64-to-tsv' },
//       { name: 'Binary to Base64', to: 'binary-to-base64' },
//       { name: 'Base64 to Binary', to: 'base64-to-binary' },
//       { name: 'Hex to Base64', to: 'hex-to-base64' },
//       { name: 'Base64 to Hex', to: 'base64-to-hex' },
//       { name: 'Octal to Base64', to: 'octal-to-base64' },
//       { name: 'More Base64 Tools', to: 'more-base64-tools' }
//     ]
//   },
//   {
//     name: 'Image Tools',
//     subcategories: [
//       { name: 'JPG to PNG', to: 'jpg-to-png' },
//       { name: 'BMP to PNG', to: 'bmp-to-png' },
//       { name: 'PNG to JPG', to: 'png-to-jpg' },
//       { name: 'GIF Splitter', to: 'gif-splitter' },
//       { name: 'GIF Viewer', to: 'gif-viewer' },
//       { name: 'More Image Tools', to: 'more-image-tools' }
//     ]
//   },
//   {
//     name: 'Color Converters',
//     subcategories: [
//       { name: 'HEX to Pantone Converter', to: 'hextopantone' },
//       { name: 'RGB to Pantone Converter', to: 'rgbtopantone' },
//       { name: 'HSV to Pantone Converter', to: 'hsvtopantone' },
//       { name: 'CMYK to Pantone Converter', to: 'cmyktopantone' },
//       { name: 'CMYK to HEX Converter', to: 'cmyktohex' },
//       { name: 'CMYK to RGB Converter', to: 'cmyktorgb' },
//       { name: 'CMYK to HSV Converter', to: 'cmyktohsv' },
//       { name: 'HSV to HEX Converter', to: 'hsvtohex' },
//       { name: 'HSV to RGB Converter', to: 'hsvtorgb' },
//       { name: 'HSV to CMYK Converter', to: 'hsvtocmyk' },
//       { name: 'HEX to HSV Converter', to: 'hextohsv' },
//       { name: 'RGB to HEX Converter', to: 'rgbtohex' },
//       { name: 'RGB to HSV Converter', to: 'rgbtohsv' },
//       { name: 'RGB to CMYK Converter', to: 'rgbtocmyk' },
//       { name: 'HEX to RGB Converter', to: 'hextorgb' },
//       { name: 'HEX to CMYK Converter', to: 'hextocmyk' },
//       { name: 'Pantone to HEX Converter', to: 'pantonetohex' },
//       { name: 'Pantone to RGB Converter', to: 'pantonetorgb' },
//       { name: 'Pantone to CMYK Converter', to: 'pantonetocmyk' },
//       { name: 'Pantone to HSV Converter', to: 'pantonetohsv' }
//     ]
//   },
//   {
//     name: 'Unit Converter',
//     subcategories: [
//       { name: 'Length Converter', to: 'length-converter' },
//       { name: 'Weight Converter', to: 'weight-converter' },
//       { name: 'Volume Converter', to: 'volume-converter' },
//       { name: 'Area Converter', to: 'area-converter' },
//       { name: 'Time Converter', to: 'time-converter' },
//       { name: 'Unix Timestamp Converter', to: 'unix-timestamp-converter' },
//       { name: 'More Unit Tools', to: 'more-unit-tools' }
//     ]
//   },
//   {
//     name: 'SQL Converters',
//     subcategories: [
//       { name: 'SQL to CSV Converter', to: 'sql-to-csv' },
//       { name: 'SQL to JSON Converter', to: 'sql-to-json' },
//       { name: 'SQL to XML Converter', to: 'sql-to-xml' },
//       { name: 'SQL to YAML Converter', to: 'sql-to-yaml' },
//       { name: 'SQL to HTML Converter', to: 'sql-to-html' }
//     ]
//   },
//   {
//     name: 'Encode & Decode',
//     subcategories: [
//       { name: 'Base32 Encode', to: 'base32-encode' },
//       { name: 'Base32 Decode', to: 'base32-decode' },
//       { name: 'Base58 Encode', to: 'base58-encode' },
//       { name: 'Base58 Decode', to: 'base58-decode' },
//       { name: 'Base64 Encode', to: 'base64-encode' },
//       { name: 'Base64 Decode', to: 'base64-decode' },
//       { name: 'URL Encode Online', to: 'url-encode' },
//       { name: 'URL Decode Online', to: 'url-decode' },
//       { name: 'JSON URL Encode', to: 'json-url-encode' },
//       { name: 'JSON URL Decode', to: 'json-url-decode' },
//       { name: 'HTML Encode', to: 'html-encode' },
//       { name: 'HTML Decode', to: 'html-decode' },
//       { name: 'XML URL Encoding', to: 'xml-url-encode' },
//       { name: 'XML URL Decoding', to: 'xml-url-decode' },
//       { name: 'UTF8 Converter', to: 'utf8-converter' },
//       { name: 'UTF8 Decode', to: 'utf8-decode' },
//       { name: 'Hex to UTF8', to: 'hex-to-utf8' },
//       { name: 'JSON Decode Online', to: 'json-decode' },
//       { name: 'JSON Encode Online', to: 'json-encode' }
//     ]
//   },
//   {
//     name: 'Base64 Tools',
//     subcategories: [
//       { name: 'Image to Base64', to: 'image-to-base64' },
//       { name: 'Base64 to Image', to: 'base64-to-image' },
//       { name: 'PNG to Base64', to: 'png-to-base64' },
//       { name: 'JPG to Base64', to: 'jpg-to-base64' },
//       { name: 'JSON to Base64', to: 'json-to-base64' },
//       { name: 'XML to Base64', to: 'xml-to-base64' },
//       { name: 'YAML to Base64', to: 'yaml-to-base64' },
//       { name: 'Base64 to JSON', to: 'base64-to-json' },
//       { name: 'Base64 to XML', to: 'base64-to-xml' },
//       { name: 'Base64 to YAML', to: 'base64-to-yaml' },
//       { name: 'CSV to Base64', to: 'csv-to-base64' },
//       { name: 'Base64 to CSV', to: 'base64-to-csv' },
//       { name: 'TSV to Base64', to: 'tsv-to-base64' },
//       { name: 'Base64 to TSV', to: 'base64-to-tsv' },
//       { name: 'Binary to Base64', to: 'binary-to-base64' },
//       { name: 'Base64 to Binary', to: 'base64-to-binary' },
//       { name: 'Hex to Base64', to: 'hex-to-base64' },
//       { name: 'Base64 to Hex', to: 'base64-to-hex' },
//       { name: 'Octal to Base64', to: 'octal-to-base64' },
//       { name: 'More Base64 Tools', to: 'more-base64-tools' }
//     ]
//   },
//   {
//     name: 'Image Tools',
//     subcategories: [
//       { name: 'JPG to PNG', to: 'jpg-to-png' },
//       { name: 'BMP to PNG', to: 'bmp-to-png' },
//       { name: 'PNG to JPG', to: 'png-to-jpg' },
//       { name: 'GIF Splitter', to: 'gif-splitter' },
//       { name: 'GIF Viewer', to: 'gif-viewer' },
//       { name: 'More Image Tools', to: 'more-image-tools' }
//     ]
//   },
// {
//   name: 'Converters',
//   subcategories: [
//     { name: 'Image to Base64', to: 'image-to-base64' },
//     { name: 'Base64 to Image', to: 'base64-to-image' },
//     { name: 'Date Calculator', to: 'date-calculator' },
//     { name: 'EXCEL to HTML', to: 'excel-to-html' },
//     { name: 'EXCEL to XML', to: 'excel-to-xml' },
//     { name: 'EXCEL to JSON', to: 'excel-to-json' },
//     { name: 'OPML to JSON', to: 'opml-to-json' },
//     { name: 'Word to HTML', to: 'word-to-html' },
//     { name: 'Online Tableizer', to: 'online-tableizer' }
//   ]
// }
// {
//   name: 'JSON Converters',
//   subcategories: [
//     { name: 'JSON to JAVA', to: 'json-to-java' },
//     { name: 'JSON to XML', to: 'json-to-xml' },
//     { name: 'JSON to YAML', to: 'json-to-yaml' },
//     { name: 'JSON to CSV', to: 'json-to-csv' },
//     { name: 'JSON to TSV', to: 'json-to-tsv' },
//     { name: 'JSON to Text', to: 'json-to-text' },
//     { name: 'JSON to Excel', to: 'json-to-excel' },
//     { name: 'JSON to HTML', to: 'json-to-html' }
//   ]
// }
//   {
//     name: 'XML Converters',
//     subcategories: [
//       { name: 'XML Converter', to: 'xml-converter' },
//       { name: 'XML to JSON', to: 'xml-to-json' },
//       { name: 'XML to YAML', to: 'xml-to-yaml' },
//       { name: 'XML to CSV', to: 'xml-to-csv' },
//       { name: 'XML to TSV', to: 'xml-to-tsv' },
//       { name: 'XML to Text', to: 'xml-to-text' },
//       { name: 'XML-XSL Transform', to: 'xml-xsl-transform' },
//       { name: 'XML to HTML', to: 'xml-to-html' },
//       { name: 'XML to Excel', to: 'xml-to-excel' },
//       { name: 'XML to JAVA', to: 'xml-to-java' }
//     ]
//   },
//   {
//     name: 'HTML Converters',
//     subcategories: [
//       { name: 'HTML Stripper', to: 'html-stripper' },
//       { name: 'HTML Table Generator', to: 'html-table-generator' },
//       { name: 'HTML to CSV Converter', to: 'html-to-csv-converter' },
//       { name: 'HTML to TSV Converter', to: 'html-to-tsv-converter' },
//       { name: 'HTML to PHP Converter', to: 'html-to-php-converter' },
//       { name: 'HTML to CSV', to: 'html-to-csv' },
//       { name: 'HTML to JSON', to: 'html-to-json' },
//       { name: 'HTML to XML', to: 'html-to-xml' },
//       { name: 'HTML to YAML', to: 'html-to-yaml' },
//       { name: 'HTML to Text', to: 'html-to-text' },
//       { name: 'Text to HTML Entities', to: 'text-to-html-entities' },
//       { name: 'HTML Entities to Text', to: 'html-entities-to-text' },
//       { name: 'HTML to Markdown', to: 'html-to-markdown' },
//       { name: 'Markdown to HTML', to: 'markdown-to-html' },
//       { name: 'PUG to HTML Converter', to: 'pug-to-html-converter' },
//       { name: 'HTML to PUG Converter', to: 'html-to-pug-converter' },
//       { name: 'JADE to HTML Converter', to: 'jade-to-html-converter' },
//       { name: 'HTML to JADE Converter', to: 'html-to-jade-converter' },
//       { name: 'HTML to BBCode Converter', to: 'html-to-bbcode-converter' },
//       { name: 'BBCode to HTML Converter', to: 'bbcode-to-html-converter' }
//     ]
//   },
//   {
//     name: 'YAML Converters',
//     subcategories: [
//       { name: 'YAML Converter', to: 'yaml-converter' },
//       { name: 'YAML to XML', to: 'yaml-to-xml' },
//       { name: 'YAML to JSON', to: 'yaml-to-json' },
//       { name: 'YAML to CSV', to: 'yaml-to-csv' },
//       { name: 'YAML to Excel', to: 'yaml-to-excel' }
//     ]
//   },
//   {
//     name: 'Utility',
//     subcategories: [
//       { name: 'Send Snap Message', to: 'send-snap-message' },
//       { name: 'Responsive Website Tester', to: 'responsive-website-tester' },
//       { name: 'Credit Card Validator', to: 'credit-card-validator' },
//       { name: 'Credit Card Fake Number Generator', to: 'credit-card-fake-number-generator' },
//       { name: 'XPath Tester', to: 'xpath-tester' },
//       { name: 'JSON Path Tester', to: 'json-path-tester' },
//       { name: 'JSON Minifier', to: 'json-minifier' },
//       { name: 'File Difference', to: 'file-difference' },
//       { name: 'JSON Diff', to: 'json-diff' },
//       { name: 'XML Diff', to: 'xml-diff' },
//       { name: 'Broken Link Checker', to: 'broken-link-checker' },
//       { name: 'JSON Deserialize Online', to: 'json-deserialize-online' },
//       { name: 'JSON Serialize Online', to: 'json-serialize-online' },
//       { name: 'JSON Stringify Online', to: 'json-stringify-online' },
//       { name: 'XML Stringify Online', to: 'xml-stringify-online' },
//       { name: 'String to JSON Online', to: 'string-to-json-online' },
//       { name: 'JavaScript Obfuscator', to: 'javascript-obfuscator' },
//       { name: 'Curl to PHP', to: 'curl-to-php' },
//       { name: 'Crontab Format', to: 'crontab-format' }
//     ]
//   },
//   {
//     name: 'Chart Tools',
//     subcategories: [
//       { name: 'Line Graph Maker', to: 'line-graph-maker' },
//       { name: 'Bar Graph Maker', to: 'bar-graph-maker' },
//       { name: 'Pie Chart Maker', to: 'pie-chart-maker' },
//       { name: 'Doughnut Chart Maker', to: 'doughnut-chart-maker' },
//       { name: 'Scatter Plot Maker', to: 'scatter-plot-maker' }
//     ]
//   },
//   {
//     name: 'Viewers',
//     subcategories: [
//       { name: 'JSON Viewer', to: 'json-viewer' },
//       { name: 'XML Viewer', to: 'xml-viewer' },
//       { name: 'YAML Viewer', to: 'yaml-viewer' },
//       { name: 'MXML Viewer', to: 'mxml-viewer' },
//       { name: 'HTML Viewer', to: 'html-viewer' },
//       { name: 'JavaScript Viewer', to: 'javascript-viewer' },
//       { name: 'RSS Viewer', to: 'rss-viewer' },
//       { name: 'SOURCE CODE Viewer', to: 'source-code-viewer' },
//       { name: 'OPML Viewer', to: 'opml-viewer' },
//       { name: 'CSV Viewer', to: 'csv-viewer' },
//       { name: 'BBCode Viewer', to: 'bbcode-viewer' },
//       { name: 'Markdown Viewer', to: 'markdown-viewer' }
//     ]
//   },
//   {
//     name: 'Programming Editors',
//     subcategories: [
//       { name: 'XML Editor', to: 'xml-editor' },
//       { name: 'JSON Editor', to: 'json-editor' },
//       { name: 'Real Time HTML Editor', to: 'real-time-html-editor' },
//       { name: 'YAML Editor', to: 'yaml-editor' },
//       { name: 'ONLINE Editor', to: 'online-editor' },
//       { name: 'JAVA Editor', to: 'java-editor' },
//       { name: 'C# Editor', to: 'csharp-editor' },
//       { name: 'Actionscript Editor', to: 'actionscript-editor' },
//       { name: 'Markdown Editor', to: 'markdown-editor' }
//     ]
//   },
//   {
//     name: 'Parsers',
//     subcategories: [
//       { name: 'URL Parser', to: 'url-parser' },
//       { name: 'JSON Parser', to: 'json-parser' },
//       { name: 'XML Parser', to: 'xml-parser' },
//       { name: 'YAML Parser', to: 'yaml-parser' }
//     ]
//   },
//   {
//     name: 'CSS Tools',
//     subcategories: [
//       { name: 'CSS Beautifier', to: 'css-beautifier' },
//       { name: 'CSS to LESS', to: 'css-to-less' },
//       { name: 'CSS to SCSS', to: 'css-to-scss' },
//       { name: 'CSS to SASS', to: 'css-to-sass' },
//       { name: 'CSS to Stylus', to: 'css-to-stylus' },
//       { name: 'Stylus Compiler', to: 'stylus-compiler' },
//       { name: 'Stylus to CSS', to: 'stylus-to-css' },
//       { name: 'Stylus to LESS', to: 'stylus-to-less' },
//       { name: 'Stylus to SCSS', to: 'stylus-to-scss' },
//       { name: 'Stylus to SASS', to: 'stylus-to-sass' },
//       { name: 'LESS Compiler', to: 'less-compiler' },
//       { name: 'LESS to CSS', to: 'less-to-css' },
//       { name: 'LESS to Stylus', to: 'less-to-stylus' },
//       { name: 'LESS to SCSS', to: 'less-to-scss' },
//       { name: 'LESS to SASS', to: 'less-to-sass' },
//       { name: 'SCSS Compiler', to: 'scss-compiler' },
//       { name: 'SCSS to CSS', to: 'scss-to-css' },
//       { name: 'SCSS to Stylus', to: 'scss-to-stylus' },
//       { name: 'SCSS to LESS', to: 'scss-to-less' },
//       { name: 'SCSS to SASS', to: 'scss-to-sass' },
//       { name: 'SASS Compiler', to: 'sass-compiler' },
//       { name: 'SASS to CSS', to: 'sass-to-css' },
//       { name: 'SASS to Stylus', to: 'sass-to-stylus' },
//       { name: 'SASS to SCSS', to: 'sass-to-scss' },
//       { name: 'SASS to LESS', to: 'sass-to-less' }
//     ]
//   },
//   {
//     name: 'Escape Unescape',
//     subcategories: [
//       { name: 'HTML Escape Unescape', to: 'html-escape-unescape' },
//       { name: 'XML Escape Unescape', to: 'xml-escape-unescape' },
//       { name: 'Java Escape Unescape', to: 'java-escape-unescape' },
//       { name: 'C# Escape Unescape', to: 'csharp-escape-unescape' },
//       { name: 'Javascript Escape Unescape', to: 'javascript-escape-unescape' },
//       { name: 'CSV Escape Unescape', to: 'csv-escape-unescape' },
//       { name: 'SQL Escape Unescape', to: 'sql-escape-unescape' },
//       { name: 'JSON Escape Unescape', to: 'json-escape-unescape' },
//       { name: 'Un-Google Link', to: 'un-google-link' }
//     ]
//   },
//   {
//     name: 'CryptoGraphy Tools',
//     subcategories: [
//       { name: 'Encryption-Decryption', to: 'encryption-decryption' },
//       { name: 'HMAC Generator', to: 'hmac-generator' },
//       { name: 'MD2 Hash Generator', to: 'md2-hash-generator' },
//       { name: 'MD4 Hash Generator', to: 'md4-hash-generator' },
//       { name: 'MD5 Hash Generator', to: 'md5-hash-generator' },
//       { name: 'MD6 Hash Generator', to: 'md6-hash-generator' },
//       { name: 'NTLM Hash Generator', to: 'ntlm-hash-generator' },
//       { name: 'SHA1 Hash Generator', to: 'sha1-hash-generator' },
//       { name: 'SHA2 Hash Generator', to: 'sha2-hash-generator' },
//       { name: 'SHA224 Hash Generator', to: 'sha224-hash-generator' },
//       { name: 'SHA256 Hash Generator', to: 'sha256-hash-generator' },
//       { name: 'SHA384 Hash Generator', to: 'sha384-hash-generator' },
//       { name: 'SHA512 Hash Generator', to: 'sha512-hash-generator' },
//       { name: 'SHA512/224 Hash Generator', to: 'sha512-224-hash-generator' },
//       { name: 'SHA512/256 Hash Generator', to: 'sha512-256-hash-generator' },
//       { name: 'SHA3-224 Hash Generator', to: 'sha3-224-hash-generator' },
//       { name: 'SHA3-256 Hash Generator', to: 'sha3-256-hash-generator' },
//       { name: 'SHA3-384 Hash Generator', to: 'sha3-384-hash-generator' },
//       { name: 'SHA3-512 Hash Generator', to: 'sha3-512-hash-generator' },
//       { name: 'CRC-16 Hash Generator', to: 'crc-16-hash-generator' },
//       { name: 'CRC-32 Hash Generator', to: 'crc-32-hash-generator' },
//       { name: 'Shake-128 Hash Generator', to: 'shake-128-hash-generator' },
//       { name: 'Shake-256 Hash Generator', to: 'shake-256-hash-generator' },
//       { name: 'Whirlpool Hash Generator', to: 'whirlpool-hash-generator' },
//       { name: 'Wordpress Password Hash Generator', to: 'wordpress-password-hash-generator' }
//     ]
//   },
//   {
//     name: 'Beautifiers',
//     subcategories: [
//       { name: 'JSON Beautifier', to: 'json-beautifier' },
//       { name: 'CSS Beautifier', to: 'css-beautifier' },
//       { name: 'XML Beautifier', to: 'xml-beautifier' },
//       { name: 'Javascript Beautifier', to: 'javascript-beautifier' },
//       { name: 'YAML Beautifier', to: 'yaml-beautifier' },
//       { name: 'C# Beautifier', to: 'csharp-beautifier' },
//       { name: 'Java Beautifier', to: 'java-beautifier' },
//       { name: 'C Beautifier', to: 'c-beautifier' },
//       { name: 'C++ Beautifier', to: 'cpp-beautifier' },
//       { name: 'TypeScript Formatter', to: 'typescript-formatter' },
//       { name: 'SQL Formatter', to: 'sql-formatter' },
//       { name: 'Babel Formatter', to: 'babel-formatter' },
//       { name: 'Markdown Formatter', to: 'markdown-formatter' },
//       { name: 'MDX Formatter', to: 'mdx-formatter' },
//       { name: 'LESS Beautifier', to: 'less-beautifier' },
//       { name: 'SCSS Beautifier', to: 'scss-beautifier' },
//       { name: 'GraphQL Beautifier', to: 'graphql-beautifier' },
//       { name: 'PHP Beautifier', to: 'php-beautifier' },
//       { name: 'Python Beautifier', to: 'python-beautifier' },
//       { name: 'Perl Beautifier', to: 'perl-beautifier' },
//       { name: 'Ruby Beautifier', to: 'ruby-beautifier' },
//       { name: 'Angular Formatter', to: 'angular-formatter' },
//       { name: 'React Formatter', to: 'react-formatter' },
//       { name: 'Lua Beautifier', to: 'lua-beautifier' },
//       { name: 'XAML Beautifier', to: 'xaml-beautifier' }
//     ]
//   },
//   {
//     name: 'Minifier',
//     subcategories: [
//       { name: 'JSON Minify', to: 'json-minify' },
//       { name: 'XML Minify', to: 'xml-minify' },
//       { name: 'Minify JS', to: 'minify-js' },
//       { name: 'CSS Minify', to: 'css-minify' },
//       { name: 'SQL Minifier', to: 'sql-minifier' },
//       { name: 'Minify HTML', to: 'minify-html' },
//       { name: 'Lua Minifier', to: 'lua-minifier' },
//       { name: 'Text Minifier', to: 'text-minifier' }
//     ]
//   },
//   {
//     name: 'Utility',
//     subcategories: [
//       { name: 'Send Snap Message', to: 'send-snap-message' },
//       { name: 'Responsive Website Tester', to: 'responsive-website-tester' },
//       { name: 'Credit Card Validator', to: 'credit-card-validator' }
//     ]
//   },
//   {
//     name: 'Chart Tools',
//     subcategories: [
//       { name: 'Line Graph Maker', to: 'line-graph-maker' },
//       { name: 'Bar Graph Maker', to: 'bar-graph-maker' },
//       { name: 'Pie Chart Maker', to: 'pie-chart-maker' },
//       { name: 'Doughnut Chart Maker', to: 'doughnut-chart-maker' },
//       { name: 'Scatter Plot Maker', to: 'scatter-plot-maker' }
//     ]
//   },
//   {
//     name: 'Viewers',
//     subcategories: [
//       { name: 'JSON Viewer', to: 'json-viewer' },
//       { name: 'XML Viewer', to: 'xml-viewer' },
//       { name: 'YAML Viewer', to: 'yaml-viewer' },
//       { name: 'MXML Viewer', to: 'mxml-viewer' },
//       { name: 'HTML Viewer', to: 'html-viewer' },
//       { name: 'JavaScript Viewer', to: 'javascript-viewer' },
//       { name: 'RSS Viewer', to: 'rss-viewer' },
//       { name: 'SOURCE CODE Viewer', to: 'source-code-viewer' },
//       { name: 'OPML Viewer', to: 'opml-viewer' },
//       { name: 'CSV Viewer', to: 'csv-viewer' },
//       { name: 'BBCode Viewer', to: 'bbcode-viewer' },
//       { name: 'Markdown Viewer', to: 'markdown-viewer' }
//     ]
//   },
//   {
//     name: 'Programming Editors',
//     subcategories: [
//       { name: 'XML Editor', to: 'xml-editor' },
//       { name: 'JSON Editor', to: 'json-editor' },
//       { name: 'Real Time HTML Editor', to: 'real-time-html-editor' },
//       { name: 'YAML Editor', to: 'yaml-editor' },
//       { name: 'ONLINE Editor', to: 'online-editor' },
//       { name: 'JAVA Editor', to: 'java-editor' },
//       { name: 'C# Editor', to: 'csharp-editor' },
//       { name: 'Actionscript Editor', to: 'actionscript-editor' },
//       { name: 'Markdown Editor', to: 'markdown-editor' }
//     ]
//   },
//   {
//     name: 'Parsers',
//     subcategories: [
//       { name: 'URL Parser', to: 'url-parser' },
//       { name: 'JSON Parser', to: 'json-parser' },
//       { name: 'XML Parser', to: 'xml-parser' },
//       { name: 'YAML Parser', to: 'yaml-parser' }
//     ]
//   },
//   {
//     name: 'CSS Tools',
//     subcategories: [
//       { name: 'CSS Beautifier', to: 'css-beautifier' },
//       { name: 'CSS to LESS', to: 'css-to-less' },
//       { name: 'CSS to SCSS', to: 'css-to-scss' },
//       { name: 'CSS to SASS', to: 'css-to-sass' },
//       { name: 'CSS to Stylus', to: 'css-to-stylus' },
//       { name: 'Stylus Compiler', to: 'stylus-compiler' },
//       { name: 'Stylus to CSS', to: 'stylus-to-css' },
//       { name: 'Stylus to LESS', to: 'stylus-to-less' },
//       { name: 'Stylus to SCSS', to: 'stylus-to-scss' },
//       { name: 'Stylus to SASS', to: 'stylus-to-sass' },
//       { name: 'LESS Compiler', to: 'less-compiler' },
//       { name: 'LESS to CSS', to: 'less-to-css' },
//       { name: 'LESS to Stylus', to: 'less-to-stylus' },
//       { name: 'LESS to SCSS', to: 'less-to-scss' },
//       { name: 'LESS to SASS', to: 'less-to-sass' },
//       { name: 'SCSS Compiler', to: 'scss-compiler' },
//       { name: 'SCSS to CSS', to: 'scss-to-css' },
//       { name: 'SCSS to Stylus', to: 'scss-to-stylus' },
//       { name: 'SCSS to LESS', to: 'scss-to-less' },
//       { name: 'SCSS to SASS', to: 'scss-to-sass' },
//       { name: 'SASS Compiler', to: 'sass-compiler' },
//       { name: 'SASS to CSS', to: 'sass-to-css' },
//       { name: 'SASS to Stylus', to: 'sass-to-stylus' },
//       { name: 'SASS to SCSS', to: 'sass-to-scss' },
//       { name: 'SASS to LESS', to: 'sass-to-less' }
//     ]
//   },
//   {
//     name: 'Escape Unescape',
//     subcategories: [
//       { name: 'HTML Escape Unescape', to: 'html-escape-unescape' },
//       { name: 'XML Escape Unescape', to: 'xml-escape-unescape' },
//       { name: 'Java Escape Unescape', to: 'java-escape-unescape' },
//       { name: 'C# Escape Unescape', to: 'csharp-escape-unescape' },
//       { name: 'Javascript Escape Unescape', to: 'javascript-escape-unescape' },
//       { name: 'CSV Escape Unescape', to: 'csv-escape-unescape' },
//       { name: 'SQL Escape Unescape', to: 'sql-escape-unescape' },
//       { name: 'JSON Escape Unescape', to: 'json-escape-unescape' },
//       { name: 'Un-Google Link', to: 'un-google-link' }
//     ]
//   },
//   {
//     name: 'CryptoGraphy Tools',
//     subcategories: [
//       { name: 'Encryption-Decryption', to: 'encryption-decryption' },
//       { name: 'HMAC Generator', to: 'hmac-generator' },
//       { name: 'MD2 Hash Generator', to: 'md2-hash-generator' },
//       { name: 'MD4 Hash Generator', to: 'md4-hash-generator' },
//       { name: 'MD5 Hash Generator', to: 'md5-hash-generator' },
//       { name: 'MD6 Hash Generator', to: 'md6-hash-generator' },
//       { name: 'NTLM Hash Generator', to: 'ntlm-hash-generator' },
//       { name: 'SHA1 Hash Generator', to: 'sha1-hash-generator' },
//       { name: 'SHA2 Hash Generator', to: 'sha2-hash-generator' },
//       { name: 'SHA224 Hash Generator', to: 'sha224-hash-generator' },
//       { name: 'SHA256 Hash Generator', to: 'sha256-hash-generator' },
//       { name: 'SHA384 Hash Generator', to: 'sha384-hash-generator' },
//       { name: 'SHA512 Hash Generator', to: 'sha512-hash-generator' },
//       { name: 'SHA512/224 Hash Generator', to: 'sha512-224-hash-generator' },
//       { name: 'SHA512/256 Hash Generator', to: 'sha512-256-hash-generator' },
//       { name: 'SHA3-224 Hash Generator', to: 'sha3-224-hash-generator' },
//       { name: 'SHA3-256 Hash Generator', to: 'sha3-256-hash-generator' },
//       { name: 'SHA3-384 Hash Generator', to: 'sha3-384-hash-generator' },
//       { name: 'SHA3-512 Hash Generator', to: 'sha3-512-hash-generator' },
//       { name: 'CRC-16 Hash Generator', to: 'crc-16-hash-generator' },
//       { name: 'CRC-32 Hash Generator', to: 'crc-32-hash-generator' },
//       { name: 'Shake-128 Hash Generator', to: 'shake-128-hash-generator' },
//       { name: 'Shake-256 Hash Generator', to: 'shake-256-hash-generator' },
//       { name: 'Whirlpool Hash Generator', to: 'whirlpool-hash-generator' },
//       { name: 'Wordpress Password Hash Generator', to: 'wordpress-password-hash-generator' }
//     ]
//   },
//   {
//     name: 'Beautifiers',
//     subcategories: [
//       { name: 'JSON Beautifier', to: 'json-beautifier' },
//       { name: 'CSS Beautifier', to: 'css-beautifier' },
//       { name: 'XML Beautifier', to: 'xml-beautifier' },
//       { name: 'Javascript Beautifier', to: 'javascript-beautifier' },
//       { name: 'YAML Beautifier', to: 'yaml-beautifier' },
//       { name: 'C# Beautifier', to: 'csharp-beautifier' },
//       { name: 'Java Beautifier', to: 'java-beautifier' },
//       { name: 'C Beautifier', to: 'c-beautifier' },
//       { name: 'C++ Beautifier', to: 'cpp-beautifier' },
//       { name: 'TypeScript Formatter', to: 'typescript-formatter' },
//       { name: 'SQL Formatter', to: 'sql-formatter' },
//       { name: 'Babel Formatter', to: 'babel-formatter' },
//       { name: 'Markdown Formatter', to: 'markdown-formatter' },
//       { name: 'MDX Formatter', to: 'mdx-formatter' },
//       { name: 'LESS Beautifier', to: 'less-beautifier' },
//       { name: 'SCSS Beautifier', to: 'scss-beautifier' },
//       { name: 'GraphQL Beautifier', to: 'graphql-beautifier' },
//       { name: 'PHP Beautifier', to: 'php-beautifier' },
//       { name: 'Python Beautifier', to: 'python-beautifier' },
//       { name: 'Perl Beautifier', to: 'perl-beautifier' },
//       { name: 'Ruby Beautifier', to: 'ruby-beautifier' },
//       { name: 'Angular Formatter', to: 'angular-formatter' },
//       { name: 'React Formatter', to: 'react-formatter' },
//       { name: 'Lua Beautifier', to: 'lua-beautifier' },
//       { name: 'XAML Beautifier', to: 'xaml-beautifier' }
//     ]
//   },
//   {
//     name: 'Minifier',
//     subcategories: [
//       { name: 'JSON Minify', to: 'json-minify' },
//       { name: 'XML Minify', to: 'xml-minify' },
//       { name: 'Minify JS', to: 'minify-js' },
//       { name: 'CSS Minify', to: 'css-minify' },
//       { name: 'SQL Minifier', to: 'sql-minifier' },
//       { name: 'Minify HTML', to: 'minify-html' },
//       { name: 'Lua Minifier', to: 'lua-minifier' },
//       { name: 'Text Minifier', to: 'text-minifier' }
//     ]
//   },
//   {
//     name: 'Utility',
//     subcategories: [
//       { name: 'Send Snap Message', to: 'send-snap-message' },
//       { name: 'Responsive Website Tester', to: 'responsive-website-tester' },
//       { name: 'Credit Card Validator', to: 'credit-card-validator' }
//     ]
//   },
//   {
//     name: 'CSV Tools',
//     subcategories: [
//       { name: 'CSV Viewer', to: 'csv-viewer' },
//       { name: 'CSV to XML/JSON', to: 'csv-to-xml-json' },
//       { name: 'CSV to XML', to: 'csv-to-xml' },
//       { name: 'CSV to JSON', to: 'csv-to-json' },
//       { name: 'CSV to HTML', to: 'csv-to-html' },
//       { name: 'CSV to TSV', to: 'csv-to-tsv' },
//       { name: 'CSV to MULTILINE DATA', to: 'csv-to-multiline-data' },
//       { name: 'CSV to SQL', to: 'csv-to-sql' },
//       { name: 'CSV to Excel', to: 'csv-to-excel' }
//     ]
//   },
//   {
//     name: 'String Utilities',
//     subcategories: [
//       { name: 'Upside Down Text', to: 'upside-down-text' },
//       { name: 'Random Word Generator', to: 'random-word-generator' },
//       { name: 'NTLM Hash Generator', to: 'ntlm-hash-generator' },
//       { name: 'Password Generator', to: 'password-generator' },
//       { name: 'String Builder', to: 'string-builder' },
//       { name: 'Number to Word Converter', to: 'number-to-word-converter' },
//       { name: 'Word to Number Converter', to: 'word-to-number-converter' },
//       { name: 'WORD COUNTER', to: 'word-counter' },
//       { name: 'Word Repeater', to: 'word-repeater' },
//       { name: 'Reverse String', to: 'reverse-string' },
//       { name: 'String to Hex Converter', to: 'string-to-hex-converter' },
//       { name: 'Hex to String Converter', to: 'hex-to-string-converter' },
//       { name: 'String to Binary Converter', to: 'string-to-binary-converter' },
//       { name: 'Binary to String Converter', to: 'binary-to-string-converter' },
//       { name: 'Case Converter', to: 'case-converter' },
//       { name: 'Delimited Text Extractor', to: 'delimited-text-extractor' },
//       { name: 'Remove Accents', to: 'remove-accents' },
//       { name: 'Remove Duplicate Lines', to: 'remove-duplicate-lines' },
//       { name: 'Remove Empty Lines', to: 'remove-empty-lines' },
//       { name: 'Remove Extra Spaces', to: 'remove-extra-spaces' },
//       { name: 'Remove Whitespace', to: 'remove-whitespace' },
//       { name: 'Remove Line Breaks', to: 'remove-line-breaks' },
//       { name: 'Remove Lines Containing', to: 'remove-lines-containing' },
//       { name: 'Sort Text Lines', to: 'sort-text-lines' },
//       { name: 'Word Sorter', to: 'word-sorter' },
//       { name: 'Word Frequency Counter', to: 'word-frequency-counter' },
//       { name: 'Text Repeater', to: 'text-repeater' },
//       { name: 'Remove Punctuation', to: 'remove-punctuation' }
//     ]
//   },
//   {
//     name: 'Syntax Highlighting',
//     subcategories: [
//       { name: 'JSON Syntax Highlighting', to: 'json-syntax-highlighting' },
//       { name: 'XML Highlighter', to: 'xml-highlighter' },
//       { name: 'XML Pretty Print', to: 'xml-pretty-print' },
//       { name: 'HTML Pretty Print', to: 'html-pretty-print' },
//       { name: 'JS Pretty Print', to: 'js-pretty-print' },
//       { name: 'Code Highlighter', to: 'code-highlighter' }
//     ]
//   },
//   {
//     name: 'Compress / Decompress',
//     subcategories: [
//       { name: 'GZip Decompress Online', to: 'gzip-decompress-online' },
//       { name: 'Zlib Decompress Online', to: 'zlib-decompress-online' }
//     ]
//   },
//   {
//     name: 'Validators',
//     subcategories: [
//       { name: 'CSS Validator', to: 'css-validator' },
//       { name: 'JavaScript Validator', to: 'javascript-validator' },
//       { name: 'JSON Validator', to: 'json-validator' },
//       { name: 'JSON5 Validator', to: 'json5-validator' },
//       { name: 'XML Validator', to: 'xml-validator' },
//       { name: 'Credit Card Validator', to: 'credit-card-validator' },
//       { name: 'API Test', to: 'api-test' },
//       { name: 'YAML Validator', to: 'yaml-validator' }
//     ]
//   },
//   {
//     name: 'Number Utilities',
//     subcategories: [
//       { name: 'All Numbers Converter', to: 'all-numbers-converter' },
//       { name: 'Decimal to Binary', to: 'decimal-to-binary' },
//       { name: 'Decimal to Octal', to: 'decimal-to-octal' },
//       { name: 'Binary to Decimal', to: 'binary-to-decimal' },
//       { name: 'Binary to Hex', to: 'binary-to-hex' },
//       { name: 'Binary to Octal', to: 'binary-to-octal' },
//       { name: 'Hex to Decimal', to: 'hex-to-decimal' },
//       { name: 'Hex to Binary', to: 'hex-to-binary' },
//       { name: 'Hex to Octal', to: 'hex-to-octal' },
//       { name: 'Octal toDecimal', to: 'octal-to-decimal' },
//       { name: 'Octal to Binary', to: 'octal-to-binary' },
//       { name: 'Octal to Hex', to: 'octal-to-hex' },
//       { name: 'Binary to Text', to: 'binary-to-text' },
//       { name: 'Text to Binary', to: 'text-to-binary' },
//       { name: 'ASCII to Text', to: 'ascii-to-text' },
//       { name: 'Char to ASCII', to: 'char-to-ascii' },
//       { name: 'Reverse Hex', to: 'reverse-hex' }
//     ]
//   },
//   {
//     name: 'Bitwise Tools',
//     subcategories: [
//       { name: 'Bitwise Calculator', to: 'bitwise-calculator' },
//       { name: 'XOR Calculator', to: 'xor-calculator' },
//       { name: 'AND Calculator', to: 'and-calculator' },
//       { name: 'NAND Calculator', to: 'nand-calculator' },
//       { name: 'OR Calculator', to: 'or-calculator' },
//       { name: 'NOR Calculator', to: 'nor-calculator' },
//       { name: 'XNOR Calculator', to: 'xnor-calculator' }
//     ]
//   },
//   {
//     name: 'IP Tools',
//     subcategories: [
//       { name: 'Hex to IP', to: 'hex-to-ip' },
//       { name: 'IP to Hex', to: 'ip-to-hex' },
//       { name: 'Binary to IP', to: 'binary-to-ip' },
//       { name: 'IP to Binary', to: 'ip-to-binary' },
//       { name: 'Decimal to IP', to: 'decimal-to-ip' },
//       { name: 'IP to Decimal', to: 'ip-to-decimal' },
//       { name: 'Octal to IP', to: 'octal-to-ip' },
//       { name: 'IP to Octal', to: 'ip-to-octal' },
//       { name: 'IPV6 to Binary', to: 'ipv6-to-binary' }
//     ]
//   },
//   {
//     name: 'Other Tools',
//     subcategories: [
//       { name: 'Lorem-Ipsum', to: 'lorem-ipsum' },
//       { name: 'Sharelink Generator', to: 'sharelink-generator' },
//       { name: 'Hostname to IP', to: 'hostname-to-ip' },
//       { name: 'IP to Hostname', to: 'ip-to-hostname' },
//       { name: 'Phone to IP Address', to: 'phone-to-ip-address' },
//       { name: 'IP Address to Phone', to: 'ip-address-to-phone' },
//       { name: 'DNS Lookup', to: 'dns-lookup' },
//       { name: 'MX Lookup', to: 'mx-lookup' },
//       { name: 'Nameserver Lookup', to: 'nameserver-lookup' },
//       { name: 'Website to IP Address', to: 'website-to-ip-address' },
//       { name: 'Open Port Checker', to: 'open-port-checker' },
//       { name: 'Webcam Test', to: 'webcam-test' }
//     ]
//   },
//   {
//     name: 'Random Tools',
//     subcategories: [
//       { name: 'Random IP Address', to: 'random-ip-address' },
//       { name: 'Random Time Generator', to: 'random-time-generator' },
//       { name: 'Random UUID Generator', to: 'random-uuid-generator' },
//       { name: 'Random JSON Generator', to: 'random-json-generator' },
//       { name: 'Random XML Generator', to: 'random-xml-generator' },
//       { name: 'Random Data from Regex', to: 'random-data-from-regex' },
//       { name: 'Random CSV Generator', to: 'random-csv-generator' },
//       { name: 'Random Number Generator', to: 'random-number-generator' },
//       { name: 'Random Integer Generator', to: 'random-integer-generator' },
//       { name: 'Random Prime Generator', to: 'random-prime-generator' },
//       { name: 'Random Date Generator', to: 'random-date-generator' },
//       { name: 'Random Bitmap Generator', to: 'random-bitmap-generator' },
//       { name: 'Random Name Picker', to: 'random-name-picker' },
//       { name: 'Text Lines shuffler', to: 'text-lines-shuffler' },
//       { name: 'MAC Address Generator', to: 'mac-address-generator' },
//       { name: 'Random Hex Generator', to: 'random-hex-generator' },
//       { name: 'Random TSV Generator', to: 'random-tsv-generator' },
//       { name: 'Random String Generator', to: 'random-string-generator' },
//       { name: 'Random Fraction Generator', to: 'random-fraction-generator' },
//       { name: 'Random Integer Range Generator', to: 'random-integer-range-generator' },
//       { name: 'Random Binary Generator', to: 'random-binary-generator' },
//       { name: 'Random Byte Generator', to: 'random-byte-generator' },
//       { name: 'Random Decimal Generator', to: 'random-decimal-generator' },
//       { name: 'Random Alphanumeric Generator', to: 'random-alphanumeric-generator' }
//     ]
//   }
// ];